import type React from 'react'

// Config-form field, input, button, and AI-button styles.
// Ported verbatim from src/renderer/components/loop/LoopPanel.styles.ts.
export const formStyles: Record<string, React.CSSProperties> = {
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-xs)',
  },
  label: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  input: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    padding: '6px 8px',
    fontSize: 'var(--type-ui-small)',
    fontFamily: 'var(--font-mono)',
  },
  textarea: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    padding: '8px 10px',
    fontSize: 'var(--type-ui-small)',
    fontFamily: 'var(--font-mono)',
    minHeight: 96,
    resize: 'vertical',
    lineHeight: 1.5,
  },
  labelRow: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 'var(--space-sm)',
  },
  labelHint: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'none',
    letterSpacing: 0,
  },
  labelActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
  },
  aiButton: {
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    color: 'var(--accent)',
    borderRadius: 'var(--radius-sm)',
    padding: '2px 8px',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-sans)',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    transition: 'background 150ms ease, color 150ms ease',
  },
  aiButtonDisabled: {
    cursor: 'default',
    opacity: 0.6,
  },
  aiButtonBusy: {
    cursor: 'progress',
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
    animation: 'ai-pulse 1.4s ease-in-out infinite',
  },
  aiSparkle: {
    display: 'inline-block',
    transformOrigin: 'center',
  },
  aiSparkleBusy: {
    animation: 'spin 1.6s linear infinite',
  },
  inputRow: {
    display: 'flex',
    gap: 'var(--space-sm)',
  },
  checkboxRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 'var(--space-sm)',
    padding: 'var(--space-xs) 0',
  },
  checkbox: {
    marginTop: 3,
    accentColor: 'var(--accent)',
    cursor: 'pointer',
  },
  checkboxLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-primary)',
    cursor: 'pointer',
  },
  checkboxHint: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    lineHeight: 1.4,
  },
  select: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    padding: '6px 8px',
    fontSize: 'var(--type-ui-small)',
  },
  primaryButton: {
    background: 'linear-gradient(135deg, var(--btn-bg), var(--btn-hover))',
    color: 'var(--btn-text)',
    border: 'none',
    height: 'var(--control-height)',
    borderRadius: 'var(--radius-sm)',
    padding: '0 var(--space-md)',
    fontSize: 'var(--type-ui-small)',
    cursor: 'pointer',
    transition: 'filter 200ms ease',
  },
  secondaryButton: {
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    color: 'var(--text-secondary)',
    height: 'var(--control-height)',
    borderRadius: 'var(--radius-sm)',
    padding: '0 var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    cursor: 'pointer',
    transition: 'background 200ms ease, color 200ms ease',
  },
}
