import type React from 'react'

// Panel chrome, status bar, intro, pending-iteration card, and disclosure styles.
// (Originally lifted from the built-in loop panel, removed in #447; this is now canonical.)
export const panelStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-sans)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 'var(--space-xs) var(--space-sm)',
    background: 'var(--bg-chrome)',
    borderBottom: '1px solid var(--border)',
    minHeight: 32,
  },
  title: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerActions: {
    display: 'flex',
    gap: 'var(--space-xs)',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: 'var(--space-sm)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
    gap: 'var(--space-sm)',
    padding: 'var(--space-lg)',
    textAlign: 'center',
  },
  emptyGlyph: {
    fontSize: 28,
    color: 'var(--text-muted)',
    opacity: 0.5,
  },
  startError: {
    padding: 'var(--space-xs) var(--space-sm)',
    border: '1px solid var(--status-error)',
    borderRadius: 4,
    color: 'var(--status-error)',
    fontSize: 'var(--type-ui-caption)',
  },
  bestBadge: {
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
  },
  introSection: {
    display: 'flex',
    gap: 'var(--space-sm)',
    alignItems: 'flex-start',
  },
  introTag: {
    color: 'var(--accent)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    minWidth: 48,
    paddingTop: 2,
  },
  introTagMuted: {
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    minWidth: 48,
    paddingTop: 2,
  },
  disclosure: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  },
  disclosureSummary: {
    cursor: 'pointer',
    padding: 'var(--space-xs) var(--space-sm)',
    color: 'var(--text-secondary)',
    fontSize: 'var(--type-ui-caption)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    userSelect: 'none',
  },
  disclosureBody: {
    padding: '0 var(--space-sm) var(--space-sm)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
}
