import type React from 'react'

// Panel chrome, status bar, intro, pending-iteration card, and disclosure styles.
// Ported verbatim from src/renderer/components/loop/LoopPanel.styles.ts.
export const panelStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-sans)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 'var(--space-xs) var(--space-sm)',
    background: 'var(--bg-chrome)',
    borderBottom: '1px solid var(--border)',
    minHeight: 32,
  },
  title: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerActions: {
    display: 'flex',
    gap: 'var(--space-xs)',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: 'var(--space-sm)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
    gap: 'var(--space-sm)',
    padding: 'var(--space-lg)',
    textAlign: 'center',
  },
  statusBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    padding: 'var(--space-xs) var(--space-sm)',
    background: 'var(--bg-secondary)',
    borderBottom: '1px solid var(--divider)',
    fontSize: 'var(--type-ui-small)',
  },
  statusBarRunning: {
    position: 'relative',
    overflow: 'hidden',
  },
  statusBarShimmer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    overflow: 'hidden',
  },
  statusBarShimmerFill: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '25%',
    background: 'linear-gradient(90deg, transparent, var(--status-running), transparent)',
    animation: 'loop-progress-sweep 1.8s ease-in-out infinite',
  },
  stateDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    flexShrink: 0,
  },
  bestBadge: {
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
  },
  intro: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    padding: 'var(--space-sm) var(--space-md)',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  introTitle: {
    color: 'var(--text-primary)',
    fontSize: 'var(--type-ui-small)',
    fontWeight: 500,
  },
  introSection: {
    display: 'flex',
    gap: 'var(--space-sm)',
    alignItems: 'flex-start',
  },
  introTag: {
    color: 'var(--accent)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    minWidth: 48,
    paddingTop: 2,
  },
  introTagMuted: {
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    minWidth: 48,
    paddingTop: 2,
  },
  pendingCard: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    padding: 'var(--space-md)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  pendingHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-primary)',
  },
  pendingPulse: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: 'var(--status-running)',
    animation: 'dot-blink 1.4s ease-in-out infinite',
    flexShrink: 0,
  },
  pendingMeta: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    gap: '4px var(--space-md)',
    fontSize: 'var(--type-ui-small)',
    alignItems: 'baseline',
  },
  pendingMetaLabel: {
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    fontSize: 'var(--type-ui-caption)',
    letterSpacing: 0.4,
  },
  pendingMetaValue: {
    color: 'var(--text-secondary)',
    fontFamily: 'var(--font-mono)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  pendingHint: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    lineHeight: 1.5,
  },
  pendingProgressTrack: {
    position: 'relative',
    height: 3,
    background: 'var(--bg-secondary)',
    borderRadius: 'var(--radius-xs)',
    overflow: 'hidden',
  },
  pendingProgressBar: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '25%',
    background: 'linear-gradient(90deg, transparent, var(--accent), transparent)',
    animation: 'loop-progress-sweep 1.8s ease-in-out infinite',
  },
  disclosure: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  },
  disclosureSummary: {
    cursor: 'pointer',
    padding: 'var(--space-xs) var(--space-sm)',
    color: 'var(--text-secondary)',
    fontSize: 'var(--type-ui-caption)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    userSelect: 'none',
  },
  disclosureBody: {
    padding: '0 var(--space-sm) var(--space-sm)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
}
