import type React from 'react'

export const modalStyles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  panel: {
    background: 'var(--bg-primary)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    width: '480px',
    maxWidth: '90vw',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: '1px solid var(--border)',
  },
  title: {
    fontWeight: 600,
    fontSize: '14px',
  },
  closeButton: {
    fontSize: '18px',
    color: 'var(--text-secondary)',
    padding: '0 4px',
    lineHeight: 1,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
  },
  body: {
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  textarea: {
    padding: '8px 10px',
    fontSize: '13px',
    lineHeight: 1.5,
    minHeight: '80px',
    resize: 'vertical',
    color: 'var(--text-primary)',
    background: 'var(--bg-input)',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    fontFamily: 'inherit',
  },
  hint: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    margin: 0,
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    fontSize: '12px',
    color: 'var(--text-secondary)',
    fontWeight: 500,
  },
  select: {
    padding: '6px 8px',
    fontSize: '13px',
    color: 'var(--text-primary)',
    background: 'var(--bg-input)',
    border: '1px solid var(--border)',
    borderRadius: '4px',
  },
  advancedToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
    color: 'var(--text-secondary)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
  },
  input: {
    padding: '6px 8px',
    fontSize: '13px',
    fontFamily: 'var(--font-mono)',
    color: 'var(--text-primary)',
    background: 'var(--bg-input)',
    border: '1px solid var(--border)',
    borderRadius: '4px',
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
    padding: '12px 16px',
    borderTop: '1px solid var(--border)',
  },
  cancelButton: {
    padding: '6px 16px',
    borderRadius: '4px',
    fontSize: '13px',
    color: 'var(--text-secondary)',
    background: 'var(--bg-input)',
    border: '1px solid var(--border)',
    cursor: 'pointer',
  },
  startButton: {
    padding: '6px 20px',
    borderRadius: '4px',
    fontSize: '13px',
    color: 'var(--accent-text)',
    background: 'var(--accent)',
    fontWeight: 500,
    cursor: 'pointer',
  },
  tabBar: {
    display: 'flex',
    gap: '0',
    borderBottom: '1px solid var(--border)',
    padding: '0 16px',
  },
  tab: {
    padding: '8px 16px',
    fontSize: '12px',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
    transition: 'color 0.15s, border-color 0.15s',
  },
  tabActive: {
    color: 'var(--text-primary)',
    borderBottomColor: 'var(--accent)',
  },
  subTabBar: {
    display: 'flex',
    gap: '4px',
    marginBottom: '4px',
  },
  subTab: {
    padding: '4px 12px',
    fontSize: '11px',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    background: 'var(--bg-input)',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  subTabActive: {
    color: 'var(--text-primary)',
    background: 'var(--bg-tertiary, var(--bg-input))',
    borderColor: 'var(--accent)',
  },
  errorText: {
    color: 'var(--error, #f85149)',
    fontSize: '12px',
    margin: 0,
  },
  worktreeHint: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '6px',
    fontSize: '12px',
    color: 'var(--text-secondary)',
    background: 'var(--bg-input)',
    borderLeft: '3px solid var(--accent)',
    borderRadius: '2px',
    padding: '8px 10px',
    margin: 0,
    lineHeight: 1.5,
  },
  worktreeHintIcon: {
    flexShrink: 0,
    color: 'var(--accent)',
    fontSize: '13px',
    fontWeight: 700,
  },
  worktreeHintBranch: {
    fontFamily: 'var(--font-mono)',
    color: 'var(--text-primary)',
    fontWeight: 500,
  },
}
