import type React from 'react'

export const sidebarStyles: Record<string, React.CSSProperties> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  list: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '4px 0',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px 4px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    color: 'var(--text-secondary)',
    marginTop: '4px',
    borderLeft: '2px solid transparent',
  },
  itemActive: {
    borderLeftColor: 'var(--accent)',
    color: 'var(--text-primary)',
  },
  itemName: {
    flex: 1,
    minWidth: 0,
  },
  itemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: '4px',
    flexShrink: 0,
  },
  removeButton: {
    fontSize: '14px',
    color: 'var(--text-muted)',
    padding: '0 2px',
    lineHeight: 1,
    opacity: 0.6,
  },
  agentItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '8px',
    padding: '5px 12px 5px 20px',
    cursor: 'pointer',
    margin: '0',
    width: '100%',
    borderRadius: 0,
    textAlign: 'left' as const,
    transition: 'background 0.1s ease',
    fontSize: '12px',
    color: 'var(--text-primary)',
  },
  agentBranch: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-mono)',
    fontSize: '12px',
  },
  agentRuntime: {
    fontSize: '11px',
    flexShrink: 0,
  },
  agentDeleteButton: {
    fontSize: '14px',
    color: 'var(--text-muted)',
    padding: '0 2px',
    lineHeight: 1,
    opacity: 0.6,
    flexShrink: 0,
    cursor: 'pointer',
  },
  empty: {
    padding: '16px 12px',
    color: 'var(--text-muted)',
    fontSize: '12px',
    textAlign: 'center' as const,
  },
  actions: {
    display: 'flex',
    gap: '4px',
    padding: '8px',
    borderTop: '1px solid var(--border)',
  },
  actionButtonPrimary: {
    flex: 1,
    padding: '6px 8px',
    background: 'var(--bg-input)',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--accent)',
    textAlign: 'center' as const,
  },
  actionButton: {
    flex: 1,
    padding: '6px 8px',
    background: 'var(--bg-input)',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    fontSize: '12px',
    color: 'var(--text-primary)',
    textAlign: 'center' as const,
  },
  cloneForm: {
    display: 'flex',
    padding: '0 8px 8px',
    gap: '4px',
  },
  cloneInput: {
    flex: 1,
    fontSize: '12px',
    padding: '4px 8px',
  },
  cloneSubmit: {
    padding: '4px 10px',
    background: 'var(--accent)',
    color: 'var(--accent-text)',
    borderRadius: '4px',
    fontSize: '12px',
  },
  fetchMessage: {
    padding: '2px 12px 4px 20px',
    fontSize: '10px',
    color: 'var(--text-muted)',
  },
}
