import type React from 'react'

export const sidebarStyles: Record<string, React.CSSProperties> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 12px 8px',
    borderBottom: '1px solid var(--border)',
  },
  title: {
    fontWeight: 600,
    fontSize: '12px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    color: 'var(--text-secondary)',
  },
  gearButton: {
    fontSize: '16px',
    color: 'var(--text-secondary)',
    padding: '2px',
    lineHeight: 1,
  },
  list: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '4px 0',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '6px 12px',
    cursor: 'pointer',
    borderRadius: '4px',
    margin: '1px 4px',
    transition: 'background 0.1s ease',
    fontSize: '13px',
  },
  itemName: {
    flex: 1,
    minWidth: 0,
  },
  itemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: '4px',
    flexShrink: 0,
  },
  badge: {
    background: 'var(--accent)',
    color: '#ffffff',
    borderRadius: '10px',
    fontSize: '10px',
    padding: '0 6px',
    minWidth: '18px',
    textAlign: 'center' as const,
    lineHeight: '18px',
  },
  removeButton: {
    fontSize: '14px',
    color: 'var(--text-muted)',
    padding: '0 2px',
    lineHeight: 1,
    opacity: 0.6,
  },
  agentItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 12px 4px 28px',
    cursor: 'pointer',
    borderRadius: '4px',
    margin: '1px 4px',
    transition: 'background 0.1s ease',
    fontSize: '12px',
  },
  agentBranch: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-mono)',
    fontSize: '11px',
  },
  agentRuntime: {
    fontSize: '10px',
    color: 'var(--text-secondary)',
    flexShrink: 0,
  },
  newAgentButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 12px 4px 28px',
    fontSize: '11px',
    color: 'var(--accent)',
    cursor: 'pointer',
  },
  empty: {
    padding: '16px 12px',
    color: 'var(--text-muted)',
    fontSize: '12px',
    textAlign: 'center' as const,
  },
  actions: {
    display: 'flex',
    gap: '4px',
    padding: '8px',
    borderTop: '1px solid var(--border)',
  },
  actionButton: {
    flex: 1,
    padding: '6px 8px',
    background: 'var(--bg-input)',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    fontSize: '12px',
    color: 'var(--text-primary)',
    textAlign: 'center' as const,
  },
  cloneForm: {
    display: 'flex',
    padding: '0 8px 8px',
    gap: '4px',
  },
  cloneInput: {
    flex: 1,
    fontSize: '12px',
    padding: '4px 8px',
  },
  cloneSubmit: {
    padding: '4px 10px',
    background: 'var(--accent)',
    color: '#ffffff',
    borderRadius: '4px',
    fontSize: '12px',
  },
}
