import type React from 'react'

export const titleBarSearchStyles: Record<string, React.CSSProperties> = {
  wrap: {
    // @ts-expect-error -- Electron-specific CSS property; opt out of window drag
    WebkitAppRegion: 'no-drag',
    position: 'relative',
    width: 'min(440px, 46%)',
  },
  field: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    height: 28,
    padding: '0 var(--space-sm) 0 var(--space-md)',
    background: 'var(--bg-input)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-pill)',
    color: 'var(--text-muted)',
    transition: 'border-color 150ms ease, box-shadow 150ms ease, color 150ms ease',
  },
  fieldFocused: {
    borderColor: 'var(--accent)',
    boxShadow: '0 0 0 2px var(--accent-subtle), 0 0 10px var(--accent-subtle)',
    color: 'var(--accent)',
  },
  input: {
    flex: 1,
    minWidth: 0,
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-sans)',
    fontSize: 'var(--type-ui-small)',
  },
  iconWrap: {
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
  },
  clearBtn: {
    border: 'none',
    background: 'transparent',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: 11,
    lineHeight: 1,
    padding: '0 2px',
    flexShrink: 0,
  },
  dropdown: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    right: 0,
    background: 'var(--bg-overlay)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-md)',
    boxShadow: 'var(--shadow-overlay)',
    overflow: 'hidden',
    zIndex: 50,
    animation: 'toast-slide-up 160ms ease',
  },
  scopes: {
    display: 'flex',
    gap: 6,
    padding: 'var(--space-sm) var(--space-md)',
    borderBottom: '1px solid var(--divider)',
  },
  scope: {
    fontSize: 'var(--type-ui-caption)',
    padding: '2px 10px',
    borderRadius: 'var(--radius-pill)',
    border: '1px solid var(--control-border)',
    background: 'transparent',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    transition: 'background 150ms ease, color 150ms ease',
  },
  scopeActive: {
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
  },
  results: {
    maxHeight: 320,
    overflowY: 'auto',
    padding: 'var(--space-xs)',
  },
  groupLabel: {
    fontSize: 'var(--type-ui-micro)',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: 'var(--text-muted)',
    padding: '6px 10px 3px',
  },
  empty: {
    padding: '14px 10px',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-muted)',
  },
  errorText: {
    padding: '14px 10px',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--error)',
  },
  result: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    padding: '8px 10px',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    transition: 'background 150ms ease, color 150ms ease',
  },
  resultActive: {
    background: 'var(--list-hover-bg)',
    color: 'var(--text-primary)',
  },
  resultIcon: {
    color: 'var(--text-muted)',
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
  },
  resultBody: {
    minWidth: 0,
    flex: 1,
  },
  resultTitle: {
    fontSize: 'var(--type-ui-small)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  resultMeta: {
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  mark: {
    color: 'var(--accent)',
    background: 'var(--accent-subtle)',
    borderRadius: 'var(--radius-xs)',
    padding: '0 1px',
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-md)',
    padding: 'var(--space-sm) var(--space-md)',
    borderTop: '1px solid var(--divider)',
    background: 'var(--bg-chrome)',
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
  },
  fkbd: {
    fontFamily: 'var(--font-mono)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-xs)',
    padding: '1px 5px',
    marginRight: 4,
  },
}
