import type React from 'react'

export const titleBarStyles: Record<string, React.CSSProperties> = {
  container: {
    height: 38,
    display: 'flex',
    alignItems: 'center',
    padding: '0 12px',
    background:
      'linear-gradient(180deg, var(--bg-chrome, var(--bg-secondary)) 0%, var(--bg-chrome-lo, var(--bg-secondary)) 100%)',
    borderBottom: '1px solid var(--border)',
    userSelect: 'none',
    // @ts-expect-error -- Electron-specific CSS property for window dragging
    WebkitAppRegion: 'drag',
  },
  trafficLightSpacer: {
    width: 78,
    flexShrink: 0,
  },
  titleArea: {
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 0,
  },
  title: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-muted)',
  },
  titleButton: {
    // @ts-expect-error -- Electron-specific CSS property; opt out of window drag
    WebkitAppRegion: 'no-drag',
    maxWidth: '60%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    background: 'transparent',
    border: '1px solid transparent',
    borderRadius: 'var(--radius-sm)',
    padding: '2px 10px',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-secondary)',
    cursor: 'text',
    transition: 'background 150ms ease, color 150ms ease',
  },
  titleButtonHover: {
    background: 'var(--list-hover-bg)',
    color: 'var(--text-primary)',
  },
  titleInput: {
    // @ts-expect-error -- Electron-specific CSS property; opt out of window drag
    WebkitAppRegion: 'no-drag',
    minWidth: 140,
    maxWidth: '60%',
    background: 'var(--bg-input)',
    border: '1px solid var(--accent)',
    borderRadius: 'var(--radius-sm)',
    padding: '2px 10px',
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--text-primary)',
    textAlign: 'center',
    outline: 'none',
  },
  themesGroup: {
    // @ts-expect-error -- Electron-specific CSS property; opt out of window drag
    WebkitAppRegion: 'no-drag',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginRight: 6,
    cursor: 'pointer',
  },
  themesLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.02em',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
  },
  themesSelect: {
    height: 26,
    padding: '0 26px 0 10px',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    background: 'transparent',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.02em',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    appearance: 'none',
    WebkitAppearance: 'none',
    backgroundImage:
      'url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\' width=\'10\' height=\'6\' viewBox=\'0 0 10 6\'><path d=\'M1 1l4 4 4-4\' fill=\'none\' stroke=\'%23999\' stroke-width=\'1.5\' stroke-linecap=\'round\' stroke-linejoin=\'round\'/></svg>")',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 9px center',
    outline: 'none',
    transition: 'background-color 150ms ease, color 150ms ease, border-color 150ms ease',
  },
  themesSelectHover: {
    backgroundColor: 'var(--list-hover-bg)',
    color: 'var(--text-primary)',
    borderColor: 'var(--control-border)',
  },
  themeToggle: {
    // @ts-expect-error -- Electron-specific CSS property; opt out of window drag
    WebkitAppRegion: 'no-drag',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 26,
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    background: 'transparent',
    fontSize: 13,
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    transition: 'background 150ms ease, color 150ms ease',
  },
  themeToggleHover: {
    background: 'var(--list-hover-bg)',
    color: 'var(--text-primary)',
  },
}
