import type React from 'react'

export const shellTabStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  headerTabBar: {
    display: 'flex',
    alignItems: 'stretch',
    alignSelf: 'stretch',
    minWidth: 0,
    gap: 0,
  },
  headerActions: {
    display: 'flex',
    alignItems: 'stretch',
    alignSelf: 'stretch',
    minWidth: 0,
  },
  headerAddButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '30px',
    padding: 0,
    fontSize: '1.1em',
    fontFamily: 'inherit',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    borderRight: '1px solid var(--border)',
    flexShrink: 0,
  },
  promptToggleLabel: {
    display: 'flex',
    alignItems: 'center',
    alignSelf: 'stretch',
    gap: '6px',
    padding: '0 10px',
    fontSize: 'inherit',
    fontFamily: 'inherit',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    borderLeft: '1px solid var(--border)',
    flexShrink: 0,
  },
  promptToggleInput: {
    width: '12px',
    height: '12px',
    margin: 0,
    accentColor: 'var(--accent)',
    cursor: 'pointer',
  },
  promptToggleText: {
    lineHeight: 1,
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    padding: '4px 8px',
    fontSize: 'inherit',
    fontFamily: 'inherit',
    color: 'var(--text-muted)',
    borderRight: '1px solid var(--border)',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  tabActive: {
    color: 'var(--text-primary)',
    background: 'var(--bg-primary)',
  },
  tabCloseButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '14px',
    height: '14px',
    borderRadius: '2px',
    color: 'var(--text-muted)',
    fontSize: 'inherit',
    lineHeight: 1,
    cursor: 'pointer',
    marginLeft: '4px',
    flexShrink: 0,
    padding: 0,
  },
  closeButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '18px',
    height: '18px',
    borderRadius: '3px',
    color: 'var(--text-muted)',
    fontSize: '14px',
    lineHeight: 1,
    cursor: 'pointer',
    marginRight: '4px',
  },
  terminalArea: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative' as const,
  },
  terminalContainer: {
    width: '100%',
    height: '100%',
    padding: '8px',
    boxSizing: 'border-box' as const,
  },
}
