import type React from 'react'

export const shellTabStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  headerTabBar: {
    display: 'flex',
    alignItems: 'stretch',
    alignSelf: 'stretch',
    minWidth: 0,
    gap: 0,
  },
  headerActions: {
    display: 'flex',
    alignItems: 'stretch',
    alignSelf: 'stretch',
    minWidth: 0,
  },
  headerAddMenu: {
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
    alignSelf: 'stretch',
    flexShrink: 0,
  },
  // The same pill the dock's header controls use (see `.dock-tab__close` /
  // `.dock-header-collapse` in theme.css): a 24px rounded square centered in the
  // 30px strip, rather than a full-height button with a divider rule.
  headerAddButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    height: '24px',
    padding: 0,
    fontSize: '14px',
    lineHeight: 1,
    fontFamily: 'inherit',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    borderRadius: 'var(--radius-sm)',
    flexShrink: 0,
  },
  shellTypeMenu: {
    position: 'fixed' as const,
    zIndex: 9999,
    minWidth: '168px',
    padding: '4px',
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    boxShadow: 'var(--shadow-popover)',
  },
  shellTypeMenuItem: {
    display: 'block',
    width: '100%',
    padding: '6px 8px',
    fontSize: 'inherit',
    fontFamily: 'inherit',
    color: 'var(--text-secondary)',
    textAlign: 'left' as const,
    whiteSpace: 'nowrap' as const,
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    padding: '4px 8px',
    fontSize: 'inherit',
    fontFamily: 'inherit',
    color: 'var(--text-muted)',
    borderRight: '1px solid var(--border)',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  tabActive: {
    color: 'var(--text-primary)',
    background: 'var(--bg-primary)',
  },
  tabCloseButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '14px',
    height: '14px',
    borderRadius: '2px',
    color: 'var(--text-muted)',
    fontSize: 'inherit',
    lineHeight: 1,
    cursor: 'pointer',
    marginLeft: '4px',
    flexShrink: 0,
    padding: 0,
  },
  closeButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '18px',
    height: '18px',
    borderRadius: '3px',
    color: 'var(--text-muted)',
    fontSize: '14px',
    lineHeight: 1,
    cursor: 'pointer',
    marginRight: '4px',
  },
  terminalArea: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative' as const,
  },
  terminalContainer: {
    width: '100%',
    height: '100%',
    padding: '8px',
    boxSizing: 'border-box' as const,
  },
}
