import type { CSSProperties } from 'react'

export const watchStyles: Record<string, CSSProperties> = {
  container: {
    display: 'flex', flexDirection: 'column', height: '100%',
    padding: 16, gap: 12, color: 'var(--text-default)', fontSize: 13,
    boxSizing: 'border-box',
  },
  label: { fontSize: 11, fontWeight: 600, opacity: 0.7, letterSpacing: 0.4, textTransform: 'uppercase' },
  labelRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 4 },
  aiButton: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    padding: '2px 8px', borderRadius: 4,
    border: '1px solid var(--border-subtle)',
    background: 'transparent', color: 'var(--text-default)',
    fontSize: 10, fontWeight: 600, letterSpacing: 0.4, textTransform: 'uppercase',
    cursor: 'pointer', lineHeight: 1.4,
  },
  aiButtonDisabled: { opacity: 0.4, cursor: 'not-allowed' },
  aiButtonImproving: {
    opacity: 1,
    cursor: 'progress',
    borderColor: 'var(--accent)',
    color: 'var(--accent)',
    animation: 'ai-pulse 1.4s ease-in-out infinite',
  },
  aiSpinner: {
    width: 10, height: 10,
    border: '1.5px solid currentColor',
    borderTopColor: 'transparent',
    borderRadius: '50%',
    animation: 'spin 0.6s linear infinite',
  },
  aiLabel: {
    backgroundImage: 'linear-gradient(90deg, var(--text-default) 0%, var(--accent) 50%, var(--text-default) 100%)',
    backgroundSize: '200% auto',
    WebkitBackgroundClip: 'text',
    backgroundClip: 'text',
    color: 'transparent',
    animation: 'shimmer 2s linear infinite',
  },
  input: {
    width: '100%', padding: '8px 10px', borderRadius: 6,
    background: 'var(--bg-input)', color: 'var(--text-default)',
    border: '1px solid var(--border-subtle)', fontSize: 13, outline: 'none',
    fontFamily: 'inherit', boxSizing: 'border-box',
  },
  textarea: {
    width: '100%', minHeight: 64, padding: '8px 10px', borderRadius: 6,
    background: 'var(--bg-input)', color: 'var(--text-default)',
    border: '1px solid var(--border-subtle)', fontSize: 13, outline: 'none',
    fontFamily: 'inherit', resize: 'vertical', boxSizing: 'border-box',
  },
  row: { display: 'flex', alignItems: 'center', gap: 8 },
  runButton: {
    display: 'inline-flex', alignItems: 'center', gap: 8,
    padding: '8px 16px', borderRadius: 6, border: 'none',
    background: 'var(--accent)', color: 'var(--accent-fg)',
    fontSize: 13, fontWeight: 600, cursor: 'pointer',
  },
  runButtonDisabled: { opacity: 0.5, cursor: 'not-allowed' },
  runButtonBusy: {
    cursor: 'progress',
    animation: 'ai-pulse 1.4s ease-in-out infinite',
  },
  runSpinner: {
    width: 12, height: 12,
    border: '2px solid currentColor',
    borderTopColor: 'transparent',
    borderRadius: '50%',
    animation: 'spin 0.7s linear infinite',
  },
  hint: { fontSize: 11, opacity: 0.6 },
  inputHint: { fontSize: 11, opacity: 0.55, marginTop: 4 },
  error: { color: 'var(--text-error, #d33)', fontSize: 12, marginTop: 4 },
  status: { display: 'flex', alignItems: 'center', gap: 12, fontSize: 11, opacity: 0.75, marginTop: 'auto', flexWrap: 'wrap' },
  dot: { width: 8, height: 8, borderRadius: '50%', display: 'inline-block', marginRight: 4 },
  dotOk: { background: '#3a7' },
  dotMissing: { background: '#c44' },
  logToggle: {
    alignSelf: 'flex-start',
    padding: '2px 8px', borderRadius: 4,
    border: '1px solid var(--border-subtle)',
    background: 'transparent', color: 'var(--text-default)',
    fontSize: 10, fontWeight: 600, letterSpacing: 0.4, textTransform: 'uppercase',
    cursor: 'pointer', opacity: 0.75,
  },
  installButton: {
    padding: '4px 10px', borderRadius: 4, border: '1px solid var(--border-subtle)',
    background: 'transparent', color: 'var(--text-default)',
    fontSize: 11, cursor: 'pointer', marginLeft: 'auto',
  },
  log: {
    fontFamily: 'ui-monospace, SFMono-Regular, monospace',
    fontSize: 11, opacity: 0.75,
    background: 'var(--bg-input)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 6, padding: 8,
    maxHeight: 160, overflowY: 'auto',
    whiteSpace: 'pre-wrap',
  },
  stage: { fontSize: 11, opacity: 0.75 },
}
