import type { CSSProperties } from 'react'

export const watchStyles: Record<string, CSSProperties> = {
  container: {
    display: 'flex', flexDirection: 'column', height: '100%',
    padding: 'var(--space-lg) var(--space-lg) var(--space-md)',
    gap: 'var(--space-md)',
    color: 'var(--text-primary)',
    fontSize: 'var(--type-ui)',
    boxSizing: 'border-box',
  },
  hero: {
    display: 'flex', alignItems: 'flex-start', gap: 'var(--space-md)',
    paddingBottom: 'var(--space-sm)',
  },
  heroIcon: {
    width: 36, height: 36, borderRadius: 'var(--radius-md)',
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0,
    boxShadow: 'var(--shadow-subtle)',
  },
  heroIconGlyph: {
    width: 0, height: 0,
    borderTop: '7px solid transparent',
    borderBottom: '7px solid transparent',
    borderLeft: '11px solid currentColor',
    marginLeft: 3,
  },
  heroCopy: { display: 'flex', flexDirection: 'column', gap: 2 },
  heroTitle: {
    fontSize: 'var(--type-title)', fontWeight: 600,
    color: 'var(--text-primary)',
    letterSpacing: 0.2,
    lineHeight: 1.2,
  },
  heroSubtitle: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    lineHeight: 1.45,
    maxWidth: 520,
  },
  label: { fontSize: 11, fontWeight: 600, opacity: 0.7, letterSpacing: 0.4, textTransform: 'uppercase' },
  labelRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 4 },
  inputBar: {
    display: 'flex', alignItems: 'stretch',
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-md)',
    boxShadow: 'var(--shadow-subtle)',
    overflow: 'hidden',
    transition: 'border-color 150ms ease, box-shadow 150ms ease',
  },
  inputBarFocused: {
    borderColor: 'var(--accent)',
    boxShadow: '0 0 0 2px var(--accent-subtle), var(--shadow-subtle)',
  },
  inputInline: {
    flex: 1, padding: '11px 14px', minHeight: 40,
    background: 'transparent', color: 'var(--text-primary)',
    border: 'none', outline: 'none',
    fontSize: 'var(--type-ui)', fontFamily: 'inherit',
  },
  runInline: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    gap: 8, padding: '0 var(--space-md)', minWidth: 92,
    background: 'linear-gradient(135deg, var(--accent), var(--accent-hover))',
    color: 'var(--accent-text)', border: 'none',
    fontSize: 'var(--type-ui)', fontWeight: 600,
    cursor: 'pointer', flexShrink: 0,
    transition: 'filter 200ms ease, opacity 200ms ease',
    borderLeft: '1px solid var(--border)',
  },
  runInlineDisabled: {
    opacity: 0.45, cursor: 'not-allowed',
    filter: 'saturate(0.4)',
  },
  runInlineBusy: { cursor: 'progress' },
  hintRow: {
    display: 'flex', alignItems: 'center', flexWrap: 'wrap',
    gap: 'var(--space-sm)',
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
  },
  examples: {
    display: 'flex', alignItems: 'center', flexWrap: 'wrap',
    gap: 'var(--space-xs)',
    marginTop: 'var(--space-xs)',
  },
  examplesLabel: {
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    fontWeight: 600,
    marginRight: 'var(--space-xs)',
  },
  exampleChip: {
    padding: '2px 8px', borderRadius: 'var(--radius-pill)',
    background: 'var(--bg-secondary)',
    color: 'var(--text-secondary)',
    border: '1px solid var(--border)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--type-ui-micro)',
  },
  aiButton: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    padding: '2px 8px', borderRadius: 4,
    border: '1px solid var(--border-subtle)',
    background: 'transparent', color: 'var(--text-default)',
    fontSize: 10, fontWeight: 600, letterSpacing: 0.4, textTransform: 'uppercase',
    cursor: 'pointer', lineHeight: 1.4,
  },
  aiButtonDisabled: { opacity: 0.4, cursor: 'not-allowed' },
  aiButtonImproving: {
    opacity: 1,
    cursor: 'progress',
    borderColor: 'var(--accent)',
    color: 'var(--accent)',
    animation: 'ai-pulse 1.4s ease-in-out infinite',
  },
  aiSpinner: {
    width: 10, height: 10,
    border: '1.5px solid currentColor',
    borderTopColor: 'transparent',
    borderRadius: '50%',
    animation: 'spin 0.6s linear infinite',
  },
  aiLabel: {
    backgroundImage: 'linear-gradient(90deg, var(--text-default) 0%, var(--accent) 50%, var(--text-default) 100%)',
    backgroundSize: '200% auto',
    WebkitBackgroundClip: 'text',
    backgroundClip: 'text',
    color: 'transparent',
    animation: 'shimmer 2s linear infinite',
  },
  input: {
    width: '100%', padding: '8px 10px', borderRadius: 6,
    background: 'var(--bg-input)', color: 'var(--text-default)',
    border: '1px solid var(--border-subtle)', fontSize: 13, outline: 'none',
    fontFamily: 'inherit', boxSizing: 'border-box',
  },
  textarea: {
    width: '100%', minHeight: 64, padding: '8px 10px', borderRadius: 6,
    background: 'var(--bg-input)', color: 'var(--text-default)',
    border: '1px solid var(--border-subtle)', fontSize: 13, outline: 'none',
    fontFamily: 'inherit', resize: 'vertical', boxSizing: 'border-box',
  },
  row: { display: 'flex', alignItems: 'center', gap: 8 },
  runButton: {
    display: 'inline-flex', alignItems: 'center', gap: 8,
    padding: '8px 16px', borderRadius: 6, border: 'none',
    background: 'var(--accent)', color: 'var(--accent-fg)',
    fontSize: 13, fontWeight: 600, cursor: 'pointer',
  },
  runButtonDisabled: { opacity: 0.5, cursor: 'not-allowed' },
  runButtonBusy: {
    cursor: 'progress',
    animation: 'ai-pulse 1.4s ease-in-out infinite',
  },
  runSpinner: {
    width: 12, height: 12,
    border: '2px solid currentColor',
    borderTopColor: 'transparent',
    borderRadius: '50%',
    animation: 'spin 0.7s linear infinite',
  },
  hint: { fontSize: 11, opacity: 0.6 },
  inputHint: { fontSize: 11, opacity: 0.55, marginTop: 4 },
  error: { color: 'var(--text-error, #d33)', fontSize: 12, marginTop: 4 },
  status: { display: 'flex', alignItems: 'center', gap: 12, fontSize: 11, opacity: 0.75, marginTop: 'auto', flexWrap: 'wrap' },
  dot: { width: 8, height: 8, borderRadius: '50%', display: 'inline-block', marginRight: 4 },
  dotOk: { background: '#3a7' },
  dotMissing: { background: '#c44' },
  showVideoButton: {
    alignSelf: 'flex-start',
    padding: '4px 10px', borderRadius: 4,
    border: '1px solid var(--border-subtle)',
    background: 'transparent', color: 'var(--text-default)',
    fontSize: 11, fontWeight: 600, letterSpacing: 0.4, textTransform: 'uppercase',
    cursor: 'pointer',
  },
  logToggle: {
    alignSelf: 'flex-start',
    padding: '2px 8px', borderRadius: 4,
    border: '1px solid var(--border-subtle)',
    background: 'transparent', color: 'var(--text-default)',
    fontSize: 10, fontWeight: 600, letterSpacing: 0.4, textTransform: 'uppercase',
    cursor: 'pointer', opacity: 0.75,
  },
  installButton: {
    padding: '4px 10px', borderRadius: 4, border: '1px solid var(--border-subtle)',
    background: 'transparent', color: 'var(--text-default)',
    fontSize: 11, cursor: 'pointer', marginLeft: 'auto',
  },
  log: {
    fontFamily: 'ui-monospace, SFMono-Regular, monospace',
    fontSize: 11, opacity: 0.75,
    background: 'var(--bg-input)',
    border: '1px solid var(--border-subtle)',
    borderRadius: 6, padding: 8,
    maxHeight: 160, overflowY: 'auto',
    whiteSpace: 'pre-wrap',
  },
  stage: { fontSize: 11, opacity: 0.75 },
}
