import type { WebResearchContext, WebResearchTopic } from '../../../background-agent/connectors/web/web-research-types'

export function buildResearchPrompt(
  topic: WebResearchTopic,
  context: WebResearchContext,
  maxSources: number,
  maxSuggestions: number,
): string {
  const profile = context.projectProfile
  const workflows = profile.majorWorkflows.length > 0 ? profile.majorWorkflows.join(', ') : '(none identified)'
  const stack = profile.dependencyStack.length > 0 ? profile.dependencyStack.join(', ') : '(unknown)'
  const openQuestions = profile.openQuestions.length > 0 ? profile.openQuestions.join('; ') : '(none identified)'
  const recentChanges = profile.recentChanges.length > 0 ? profile.recentChanges.join('; ') : '(none identified)'

  return [
    'You are researching the web for source-backed ideas about the project described below.',
    'The project may be any kind of repository in any domain. Do not assume a specific product category, runtime, framework, or platform unless the project profile says so.',
    'Use a strong research approach. Prefer official docs, changelogs, OSS repos, OSS issues/discussions, and strong engineering blogs.',
    'Forums and communities may be used only as supporting evidence, never as the only basis for a suggestion.',
    'If your runtime supports web search or browsing, use it. If it does not, return an empty result object with no invented sources.',
    'Do not inspect local repository files and do not run shell commands. Use only the supplied project profile and web research.',
    `Be selective and fast: do at most 3 search attempts and inspect at most ${maxSources} sources before deciding.`,
    'If you cannot find one high-trust source quickly, return no candidate suggestions for this topic.',
    'Return JSON only. Do not include markdown fences or commentary.',
    '',
    'JSON schema:',
    '{',
    '  "topicSummary": "short summary",',
    '  "findings": ["finding 1", "finding 2"],',
    '  "sources": [',
    '    {',
    '      "title": "source title",',
    '      "url": "https://...",',
    '      "type": "official_docs|changelog|oss_repo|oss_issue|oss_discussion|engineering_blog|forum|community|other",',
    '      "publishedAt": "YYYY-MM-DD or null",',
    '      "snippet": "short evidence snippet"',
    '    }',
    '  ],',
    '  "candidateSuggestions": [',
    '    {',
    '      "title": "suggestion title",',
    '      "category": "feature_opportunity|architecture_improvement|pattern_transfer|ecosystem_shift",',
    '      "summary": "short summary",',
    '      "whyItMatters": "why it matters for this project",',
    '      "whyNow": "why now or null",',
    '      "evidence": ["evidence 1", "evidence 2"],',
    '      "confidence": "low|medium|high",',
    '      "novelty": "low|medium|high",',
    '      "effort": "low|medium|high",',
    '      "impact": "low|medium|high"',
    '    }',
    '  ]',
    '}',
    '',
    `Use at most ${maxSources} sources and at most ${maxSuggestions} candidate suggestions.`,
    '',
    'Project profile:',
    `- Project: ${profile.projectName}`,
    `- Summary: ${profile.summary}`,
    `- Product type: ${profile.productType ?? '(unknown)'}`,
    `- Target user: ${profile.targetUser ?? '(unknown)'}`,
    `- Major workflows: ${workflows}`,
    `- Architecture: ${profile.architectureShape ?? '(unknown)'}`,
    `- Stack: ${stack}`,
    `- Open questions: ${openQuestions}`,
    `- Recent changes: ${recentChanges}`,
    '',
    'Research topic:',
    `- Ring: ${topic.ring}`,
    `- Title: ${topic.title}`,
    `- Query: ${topic.query}`,
    `- Rationale: ${topic.rationale}`,
    '',
    'Important rules:',
    '- Do not invent sources or URLs.',
    '- Only include a candidate suggestion if it is genuinely relevant to this project.',
    '- Prefer source-backed, concrete ideas over generic trend summaries.',
    '- Avoid exhaustive research; aim for the strongest answer you can support quickly.',
    '- Never inspect local files or execute commands for this task.',
  ].join('\n')
}
