import type React from 'react'

export const memoryStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  banner: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-xs)',
    padding: 'var(--space-sm)',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  bannerText: {
    flex: 1,
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    lineHeight: '1.45',
  },
  bannerButton: {
    minHeight: 'calc(var(--control-height) - 4px)',
    padding: '0 10px',
    fontSize: 'var(--type-ui-micro)',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--accent)',
    background: 'none',
    border: '1px solid var(--border)',
    cursor: 'pointer',
  },
  conceptChip: {
    minHeight: '20px',
    padding: '0 8px',
    fontSize: 'var(--type-ui-micro)',
    borderRadius: '8px',
    border: '1px solid rgba(156, 39, 176, 0.3)',
    background: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
  },
  conceptChipActive: {
    background: 'rgba(156, 39, 176, 0.2)',
    color: 'var(--accent)',
    borderColor: 'rgba(156, 39, 176, 0.6)',
  },
  filterBar: {
    display: 'flex',
    gap: 'var(--space-xs)',
    padding: '6px var(--space-sm)',
    borderBottom: '1px solid var(--border)',
    flexWrap: 'wrap' as const,
    flexShrink: 0,
  },
  filterChip: {
    minHeight: '20px',
    padding: '0 8px',
    fontSize: 'var(--type-ui-micro)',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
  },
  filterChipActive: {
    background: 'var(--accent)',
    color: 'var(--bg-primary)',
    borderColor: 'var(--accent)',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: 'var(--space-sm)',
  },
  errorBanner: {
    margin: '8px 8px 0',
    padding: '8px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid rgba(244, 68, 68, 0.28)',
    background: 'rgba(244, 68, 68, 0.08)',
    color: 'var(--error, #f44)',
    fontSize: 'var(--type-ui-caption)',
    lineHeight: '1.4',
    flexShrink: 0,
  },
  card: {
    padding: 'var(--space-sm)',
    marginBottom: '6px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
    cursor: 'pointer',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-xs)',
    marginBottom: '4px',
  },
  cardTitle: {
    fontSize: 'var(--type-ui-small)',
    fontWeight: 600,
    color: 'var(--text-primary)',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  typeBadge: {
    fontSize: 'var(--type-ui-micro)',
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    flexShrink: 0,
  },
  sourceBadge: {
    fontSize: 'var(--type-ui-micro)',
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
    background: 'rgba(255, 255, 255, 0.06)',
    color: 'var(--text-muted)',
    flexShrink: 0,
  },
  cardSummary: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    lineHeight: '1.4',
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
  },
  cardSummaryExpanded: {
    display: 'block',
    overflow: 'visible',
  },
  cardTimestamp: {
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
    marginTop: '4px',
  },
  expandedDetail: {
    marginTop: '8px',
    padding: 'var(--space-sm)',
    borderTop: '1px solid var(--border)',
    fontSize: 'var(--type-ui-caption)',
  },
  detailBlock: {
    marginTop: '6px',
  },
  conceptTag: {
    display: 'inline-block',
    fontSize: '9px',
    padding: '1px 5px',
    marginRight: '3px',
    marginBottom: '2px',
    borderRadius: '3px',
    background: 'rgba(156, 39, 176, 0.1)',
    color: 'var(--text-muted)',
  },
  factsList: {
    margin: '4px 0',
    paddingLeft: '16px',
    color: 'var(--text-primary)',
    fontSize: 'var(--type-ui-caption)',
    lineHeight: '1.5',
  },
  filesLabel: {
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
    marginTop: '6px',
  },
  fileTag: {
    display: 'inline-block',
    fontSize: 'var(--type-ui-micro)',
    padding: '1px 5px',
    marginRight: '4px',
    marginBottom: '2px',
    borderRadius: 'var(--radius-xs)',
    background: 'var(--bg-primary)',
    color: 'var(--text-muted)',
    fontFamily: 'monospace',
  },
  statsBar: {
    display: 'flex',
    gap: '12px',
    padding: '6px var(--space-sm)',
    borderTop: '1px solid var(--border)',
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
    flexShrink: 0,
  },
  emptyState: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
    textAlign: 'center' as const,
    padding: '20px',
  },
  errorState: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--error, #f44)',
    fontSize: 'var(--type-ui-small)',
    textAlign: 'center' as const,
    padding: '20px',
  },
  loadMoreButton: {
    display: 'block',
    width: '100%',
    minHeight: 'var(--control-height)',
    padding: '0 var(--space-sm)',
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--accent)',
    background: 'none',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
    marginTop: '4px',
  },
  deleteButton: {
    padding: '2px 6px',
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    flexShrink: 0,
  },
  clearButton: {
    minHeight: '24px',
    padding: '0 8px',
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--error, #f44)',
    background: 'none',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
  },
}
