import type React from 'react'

export const memoryStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  searchInput: {
    flex: 1,
    padding: '4px 8px',
    fontSize: '12px',
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    color: 'var(--text-primary)',
    outline: 'none',
  },
  tabBar: {
    display: 'flex',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  tab: {
    padding: '6px 12px',
    fontSize: '11px',
    color: 'var(--text-muted)',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
  },
  tabActive: {
    color: 'var(--accent)',
    borderBottomColor: 'var(--accent)',
  },
  filterBar: {
    display: 'flex',
    gap: '4px',
    padding: '6px 8px',
    borderBottom: '1px solid var(--border)',
    flexWrap: 'wrap' as const,
    flexShrink: 0,
  },
  filterChip: {
    padding: '2px 8px',
    fontSize: '10px',
    borderRadius: '10px',
    border: '1px solid var(--border)',
    background: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
  },
  filterChipActive: {
    background: 'var(--accent)',
    color: 'var(--bg-primary)',
    borderColor: 'var(--accent)',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: '8px',
  },
  errorBanner: {
    margin: '8px 8px 0',
    padding: '8px',
    borderRadius: '4px',
    border: '1px solid rgba(244, 68, 68, 0.28)',
    background: 'rgba(244, 68, 68, 0.08)',
    color: 'var(--error, #f44)',
    fontSize: '11px',
    lineHeight: '1.4',
    flexShrink: 0,
  },
  card: {
    padding: '8px',
    marginBottom: '6px',
    borderRadius: '4px',
    border: '1px solid var(--border)',
    background: 'var(--bg-secondary)',
    cursor: 'pointer',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '4px',
  },
  cardTitle: {
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  typeBadge: {
    fontSize: '9px',
    padding: '1px 5px',
    borderRadius: '8px',
    background: 'rgba(79, 195, 247, 0.12)',
    color: 'var(--accent)',
    flexShrink: 0,
  },
  sourceBadge: {
    fontSize: '9px',
    padding: '1px 5px',
    borderRadius: '8px',
    background: 'rgba(255, 255, 255, 0.06)',
    color: 'var(--text-muted)',
    flexShrink: 0,
  },
  cardSummary: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    lineHeight: '1.4',
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
  },
  cardTimestamp: {
    fontSize: '10px',
    color: 'var(--text-muted)',
    marginTop: '4px',
  },
  expandedDetail: {
    marginTop: '8px',
    padding: '8px',
    borderTop: '1px solid var(--border)',
    fontSize: '11px',
  },
  detailBlock: {
    marginTop: '6px',
  },
  factsList: {
    margin: '4px 0',
    paddingLeft: '16px',
    color: 'var(--text-primary)',
    fontSize: '11px',
    lineHeight: '1.5',
  },
  filesLabel: {
    fontSize: '10px',
    color: 'var(--text-muted)',
    marginTop: '6px',
  },
  fileTag: {
    display: 'inline-block',
    fontSize: '10px',
    padding: '1px 5px',
    marginRight: '4px',
    marginBottom: '2px',
    borderRadius: '3px',
    background: 'var(--bg-primary)',
    color: 'var(--text-muted)',
    fontFamily: 'monospace',
  },
  statsBar: {
    display: 'flex',
    gap: '12px',
    padding: '6px 8px',
    borderTop: '1px solid var(--border)',
    fontSize: '10px',
    color: 'var(--text-muted)',
    flexShrink: 0,
  },
  emptyState: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: '12px',
    textAlign: 'center' as const,
    padding: '20px',
  },
  errorState: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--error, #f44)',
    fontSize: '12px',
    textAlign: 'center' as const,
    padding: '20px',
  },
  loadMoreButton: {
    display: 'block',
    width: '100%',
    padding: '6px',
    fontSize: '11px',
    color: 'var(--accent)',
    background: 'none',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    cursor: 'pointer',
    marginTop: '4px',
  },
  deleteButton: {
    padding: '2px 6px',
    fontSize: '10px',
    color: 'var(--text-muted)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    flexShrink: 0,
  },
  clearButton: {
    padding: '4px 8px',
    fontSize: '10px',
    color: 'var(--error, #f44)',
    background: 'none',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    cursor: 'pointer',
  },
}
