import type React from 'react'
import { dialogPrimitives } from '../workbench-style-primitives'

export const searchModalStyles: Record<string, React.CSSProperties> = {
  overlay: {
    ...dialogPrimitives.overlay,
    // Top-aligned rather than centered: the field lands where the eye already
    // is and the results grow downward without shifting it.
    alignItems: 'flex-start',
    paddingTop: '12vh',
  },
  panel: {
    ...dialogPrimitives.panelBase,
    display: 'flex',
    flexDirection: 'column',
    width: 'min(720px, 92vw)',
  },
  field: {
    // No box around the input — this row is the field, closed by the divider
    // below it and the panel's own edge.
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    height: 44,
    padding: '0 var(--space-md)',
    borderBottom: '1px solid var(--divider)',
    color: 'var(--accent)',
  },
  input: {
    flex: 1,
    minWidth: 0,
    padding: '0 6px',
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-sans)',
    fontSize: 'var(--type-ui)',
  },
  iconWrap: {
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
  },
  clearBtn: {
    border: 'none',
    background: 'transparent',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    fontSize: 11,
    lineHeight: 1,
    padding: '0 2px',
    flexShrink: 0,
  },
  scopes: {
    display: 'flex',
    gap: 6,
    padding: 'var(--space-sm) var(--space-md)',
    borderBottom: '1px solid var(--divider)',
  },
  scope: {
    fontSize: 'var(--type-ui-caption)',
    padding: '2px 10px',
    borderRadius: 'var(--radius-pill)',
    border: '1px solid var(--control-border)',
    background: 'transparent',
    color: 'var(--text-muted)',
    cursor: 'pointer',
    transition: 'background 150ms ease, color 150ms ease',
  },
  scopeActive: {
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
  },
  results: {
    maxHeight: '52vh',
    overflowY: 'auto',
    padding: 'var(--space-xs)',
  },
  groupLabel: {
    fontSize: 'var(--type-ui-micro)',
    textTransform: 'uppercase',
    letterSpacing: '0.6px',
    color: 'var(--text-muted)',
    padding: '6px 10px 3px',
  },
  empty: {
    padding: '14px 10px',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-muted)',
  },
  errorText: {
    padding: '14px 10px',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--error)',
  },
  result: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    padding: '8px 10px',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    transition: 'background 150ms ease, color 150ms ease',
  },
  resultActive: {
    background: 'var(--list-hover-bg)',
    color: 'var(--text-primary)',
  },
  resultIcon: {
    color: 'var(--text-muted)',
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
  },
  resultBody: {
    minWidth: 0,
    flex: 1,
  },
  resultTitle: {
    fontSize: 'var(--type-ui-small)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  resultMeta: {
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  resultCode: {
    alignItems: 'flex-start',
  },
  code: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
    marginTop: 4,
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--type-ui-caption)',
  },
  codeLine: {
    display: 'grid',
    gridTemplateColumns: '2.5em minmax(0, 1fr)',
    gap: 'var(--space-sm)',
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
    color: 'var(--text-secondary)',
  },
  codeLineCurrent: {
    background: 'var(--control-bg-hover)',
    color: 'var(--text-primary)',
  },
  codeLineNumber: {
    textAlign: 'right',
    color: 'var(--text-muted)',
    userSelect: 'none',
  },
  codeLineText: {
    minWidth: 0,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  mark: {
    color: 'var(--accent)',
    background: 'var(--accent-subtle)',
    borderRadius: 'var(--radius-xs)',
    padding: '0 1px',
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-md)',
    padding: 'var(--space-sm) var(--space-md)',
    borderTop: '1px solid var(--divider)',
    background: 'var(--bg-chrome)',
    fontSize: 'var(--type-ui-micro)',
    color: 'var(--text-muted)',
  },
  fkbd: {
    fontFamily: 'var(--font-mono)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-xs)',
    padding: '1px 5px',
    marginRight: 4,
  },
}
