import type React from 'react'

export const searchPanelStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  toolbar: {
    display: 'flex',
    gap: 'var(--space-sm)',
    alignItems: 'center',
    padding: 'var(--space-sm)',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  input: {
    flex: 1,
    minHeight: 'var(--control-height)',
    padding: '0 var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--text-primary)',
  },
  select: {
    minHeight: 'var(--control-height)',
    padding: '0 var(--space-sm)',
    fontSize: 'var(--type-ui-caption)',
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--text-primary)',
  },
  tabBar: {
    display: 'flex',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  tab: {
    minHeight: 'calc(var(--control-height) - 2px)',
    padding: '0 var(--space-md)',
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
  },
  tabActive: {
    color: 'var(--accent)',
    borderBottomColor: 'var(--accent)',
  },
  controlsRow: {
    display: 'flex',
    gap: 'var(--space-xs)',
    flexWrap: 'wrap' as const,
    padding: '6px var(--space-sm)',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  toggle: {
    minHeight: '22px',
    padding: '0 8px',
    fontSize: 'var(--type-ui-micro)',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'none',
    color: 'var(--text-muted)',
    cursor: 'pointer',
  },
  toggleActive: {
    background: 'var(--accent)',
    borderColor: 'var(--accent)',
    color: 'var(--bg-primary)',
  },
  infoBar: {
    display: 'flex',
    gap: 'var(--space-sm)',
    alignItems: 'center',
    padding: '6px var(--space-sm)',
    borderBottom: '1px solid var(--border)',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-micro)',
    flexShrink: 0,
  },
  warning: {
    color: 'var(--warning, #f5a623)',
  },
  error: {
    color: 'var(--error, #f44)',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: 'var(--space-sm)',
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
    textAlign: 'center' as const,
    padding: '20px',
  },
  resultCard: {
    padding: 'var(--space-sm)',
    marginBottom: '6px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
  },
  resultCardButton: {
    width: '100%',
    textAlign: 'left' as const,
    font: 'inherit',
    color: 'inherit',
    cursor: 'pointer',
  },
  resultCardClickable: {
    cursor: 'pointer',
  },
  resultCardStatic: {
    cursor: 'default',
  },
  resultHeader: {
    display: 'flex',
    gap: 'var(--space-xs)',
    alignItems: 'center',
    marginBottom: '4px',
  },
  resultTitle: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    color: 'var(--text-primary)',
    fontSize: 'var(--type-ui-small)',
    fontWeight: 600,
  },
  badge: {
    padding: '1px 6px',
    fontSize: 'var(--type-ui-micro)',
    borderRadius: 'var(--radius-xs)',
    background: 'rgba(255, 255, 255, 0.06)',
    color: 'var(--text-muted)',
    flexShrink: 0,
  },
  codeBadge: {
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
  },
  resultSnippet: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    lineHeight: '1.45',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    fontFamily: "'SF Mono', 'Fira Code', Menlo, Consolas, monospace",
  },
  resultCodeBlock: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '2px',
    marginTop: '2px',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: "'SF Mono', 'Fira Code', Menlo, Consolas, monospace",
  },
  resultCodeLine: {
    display: 'grid',
    gridTemplateColumns: '44px minmax(0, 1fr)',
    gap: 'var(--space-xs)',
    alignItems: 'start',
    padding: '2px 0',
    color: 'var(--text-muted)',
  },
  resultCodeLineCurrent: {
    color: 'var(--text-primary)',
    background: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 'var(--radius-xs)',
  },
  resultCodeLineNumber: {
    textAlign: 'right' as const,
    color: 'var(--text-muted)',
    userSelect: 'none' as const,
  },
  resultCodeLineText: {
    minWidth: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  matchHighlight: {
    background: 'rgba(255, 214, 10, 0.32)',
    color: 'inherit',
    padding: 0,
  },
  resultMeta: {
    display: 'flex',
    gap: 'var(--space-xs)',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
    marginTop: '6px',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-micro)',
  },
}
