import type React from 'react'
import { searchPanelChromeStyles } from './SearchPanel.chrome.styles'

export const searchPanelStyles: Record<string, React.CSSProperties> = {
  ...searchPanelChromeStyles,
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  toolbar: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    padding: '14px 16px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  searchSurface: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '14px',
    padding: '16px',
    borderRadius: '16px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'linear-gradient(180deg, rgba(255, 255, 255, 0.05), rgba(255, 255, 255, 0.02))',
    boxShadow: '0 14px 34px rgba(0, 0, 0, 0.14)',
  },
  searchSurfaceMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '12px',
    flexWrap: 'wrap' as const,
  },
  searchSurfaceCopy: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    minWidth: 0,
    flex: '1 1 260px',
  },
  searchSurfaceEyebrow: {
    color: 'var(--text-primary)',
    fontSize: '13px',
    fontWeight: 700,
    lineHeight: 1.4,
  },
  searchSurfaceHint: {
    color: 'var(--text-secondary)',
    fontSize: '12px',
    lineHeight: 1.5,
  },
  scopeField: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
    minWidth: '160px',
    flex: '0 0 auto',
  },
  scopeLabel: {
    color: 'var(--text-muted)',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  queryRow: {
    display: 'flex',
    gap: '12px',
    alignItems: 'stretch',
    flexWrap: 'wrap' as const,
  },
  queryInputWrap: {
    flex: '1 1 340px',
    minWidth: 0,
  },
  input: {
    flex: 1,
    width: '100%',
    minHeight: '46px',
    padding: '0 16px',
    fontSize: '14px',
    fontWeight: 500,
    background: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '12px',
    color: 'var(--text-primary)',
    boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.03)',
  },
  select: {
    minHeight: '40px',
    padding: '0 14px',
    fontSize: '13px',
    fontWeight: 500,
    background: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '12px',
    color: 'var(--text-primary)',
  },
  primaryButton: {
    minHeight: '46px',
    padding: '0 18px',
    borderRadius: '12px',
    border: '1px solid var(--accent)',
    background: 'linear-gradient(180deg, var(--accent), var(--accent-hover))',
    color: 'var(--accent-text)',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 10px 22px rgba(0, 0, 0, 0.22)',
    transition: 'transform 0.15s ease, box-shadow 0.2s ease, filter 0.2s ease, opacity 0.2s ease',
  },
  primaryButtonContent: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
  primaryButtonLoading: {
    opacity: 1,
    cursor: 'progress',
    filter: 'saturate(0.92)',
  },
  primaryButtonDisabled: {
    opacity: 0.55,
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  tabBar: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap' as const,
  },
  tab: {
    minHeight: '34px',
    padding: '0 14px',
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--text-secondary)',
    background: 'rgba(255, 255, 255, 0.02)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: '999px',
    cursor: 'pointer',
  },
  tabActive: {
    color: 'var(--accent-text)',
    background: 'var(--accent)',
    borderColor: 'var(--accent)',
    boxShadow: '0 0 0 1px rgba(255, 255, 255, 0.06) inset',
  },
  filterSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
    padding: '12px 18px',
    borderBottom: '1px solid var(--border)',
    background: 'rgba(255, 255, 255, 0.02)',
    flexShrink: 0,
  },
  filterRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  filterLabel: {
    minWidth: '56px',
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
    color: 'var(--text-muted)',
  },
  filterChip: {
    minHeight: '28px',
    padding: '0 10px',
    fontSize: '12px',
    borderRadius: '999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    background: 'rgba(255, 255, 255, 0.02)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
  },
  filterChipActive: {
    background: 'var(--accent)',
    borderColor: 'var(--accent)',
    color: 'var(--bg-primary)',
  },
  controlsRow: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap' as const,
  },
  toggleGroup: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  toggle: {
    minHeight: '32px',
    padding: '0 12px',
    fontSize: '12px',
    fontWeight: 700,
    borderRadius: '999px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    background: 'rgba(255, 255, 255, 0.02)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
  },
  toggleActive: {
    background: 'var(--accent-subtle)',
    borderColor: 'var(--accent)',
    color: 'var(--accent)',
  },
  utilityButton: {
    minHeight: '32px',
    padding: '0 12px',
    fontSize: '12px',
    fontWeight: 700,
    borderRadius: '999px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'rgba(255, 255, 255, 0.03)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
  },
  utilityButtonActive: {
    background: 'var(--accent-subtle)',
    borderColor: 'var(--accent)',
    color: 'var(--accent)',
  },
  buttonDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
  },
  infoBar: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
    padding: '10px 18px',
    borderBottom: '1px solid var(--border)',
    background: 'rgba(255, 255, 255, 0.02)',
    color: 'var(--text-secondary)',
    fontSize: '12px',
    lineHeight: 1.5,
    flexShrink: 0,
  },
  warning: {
    color: 'var(--warning, #f5a623)',
    fontWeight: 600,
  },
  error: {
    color: 'var(--error, #f44)',
    fontWeight: 600,
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: '18px',
    background: 'linear-gradient(180deg, rgba(255, 255, 255, 0.01), transparent)',
  },
  section: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
    marginBottom: '20px',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '0 2px',
  },
  sectionTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: 'var(--text-primary)',
  },
  sectionCount: {
    fontSize: '11px',
    fontWeight: 700,
    color: 'var(--text-muted)',
    padding: '2px 8px',
    borderRadius: '999px',
    background: 'rgba(255, 255, 255, 0.04)',
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-secondary)',
    fontSize: '14px',
    textAlign: 'center' as const,
    lineHeight: 1.6,
    padding: '28px',
  },
  resultCard: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
    padding: '16px',
    marginBottom: '12px',
    borderRadius: '16px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'linear-gradient(180deg, rgba(255, 255, 255, 0.04), rgba(255, 255, 255, 0.02))',
    boxShadow: '0 10px 24px rgba(0, 0, 0, 0.14)',
  },
  resultCardButton: {
    width: '100%',
    textAlign: 'left' as const,
    font: 'inherit',
    color: 'inherit',
    cursor: 'pointer',
  },
  resultCardClickable: {
    cursor: 'pointer',
  },
  resultCardStatic: {
    cursor: 'default',
  },
  resultHeader: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-start',
    flexWrap: 'wrap' as const,
  },
  resultTitle: {
    flex: '1 1 260px',
    color: 'var(--text-primary)',
    fontSize: '14px',
    fontWeight: 700,
    lineHeight: 1.45,
    whiteSpace: 'normal' as const,
    wordBreak: 'break-word' as const,
  },
  badge: {
    padding: '3px 8px',
    fontSize: '11px',
    fontWeight: 700,
    borderRadius: '999px',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    background: 'rgba(255, 255, 255, 0.04)',
    color: 'var(--text-secondary)',
    flexShrink: 0,
  },
  codeBadge: {
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    borderColor: 'rgba(79, 195, 247, 0.28)',
  },
  resultSnippet: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    lineHeight: 1.65,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  resultCodeBlock: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    marginTop: '2px',
    fontSize: '12px',
    fontFamily: "'SF Mono', 'Fira Code', Menlo, Consolas, monospace",
  },
  resultCodeLine: {
    display: 'grid',
    gridTemplateColumns: '56px minmax(0, 1fr)',
    gap: '10px',
    alignItems: 'start',
    padding: '6px 8px',
    color: 'var(--text-secondary)',
    borderRadius: '10px',
    background: 'rgba(255, 255, 255, 0.02)',
  },
  resultCodeLineCurrent: {
    color: 'var(--text-primary)',
    background: 'rgba(255, 255, 255, 0.06)',
  },
  resultCodeLineNumber: {
    textAlign: 'right' as const,
    color: 'var(--text-muted)',
    userSelect: 'none' as const,
  },
  resultCodeLineText: {
    minWidth: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  matchHighlight: {
    background: 'rgba(255, 214, 10, 0.24)',
    color: 'inherit',
    padding: '0 1px',
    borderRadius: '3px',
  },
  resultMeta: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
    marginTop: '2px',
    color: 'var(--text-secondary)',
    fontSize: '11px',
    lineHeight: 1.4,
  },
  resultMetaItem: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '2px 8px',
    borderRadius: '999px',
    background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
  },
}
