import type React from 'react'

export const backgroundAgentPanelStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '12px 14px',
    borderBottom: '1px solid var(--border)',
    background: 'var(--bg-secondary)',
  },
  toolbarMeta: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  title: {
    fontSize: 13,
    fontWeight: 600,
  },
  subtitle: {
    fontSize: 11,
    color: 'var(--text-muted)',
  },
  refreshButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 10px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    fontSize: 12,
  },
  toolbarActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  clearButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 10px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: 12,
  },
  clearButtonDisabled: {
    cursor: 'default',
    opacity: 0.72,
  },
  refreshButtonDisabled: {
    cursor: 'default',
    opacity: 0.85,
  },
  buttonSpinner: {
    width: 12,
    height: 12,
  },
  content: {
    flex: 1,
    overflowY: 'auto',
    padding: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: 12,
    textAlign: 'center',
    padding: 24,
  },
  infoCard: {
    padding: 12,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  infoLabel: {
    fontSize: 11,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  infoText: {
    fontSize: 12,
    lineHeight: 1.5,
  },
  infoList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    margin: 0,
    paddingLeft: 16,
  },
  infoItem: {
    fontSize: 12,
    lineHeight: 1.5,
    color: 'var(--text-secondary)',
  },
  error: {
    color: 'var(--status-error)',
    fontSize: 12,
  },
  statusCard: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 10,
    padding: 12,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
  },
  statusBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minWidth: 0,
  },
  statusHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  statusHeadline: {
    fontSize: 12,
    color: 'var(--text-primary)',
    lineHeight: 1.5,
    fontWeight: 600,
  },
  statusStep: {
    fontSize: 10,
    color: 'var(--accent)',
    background: 'var(--accent-subtle)',
    padding: '2px 6px',
    borderRadius: 999,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  statusText: {
    fontSize: 12,
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  },
  activityList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  activityItem: {
    fontSize: 12,
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  },
  card: {
    padding: 14,
    borderRadius: 8,
    border: '1px solid var(--border)',
    background: 'var(--bg-elevated)',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: 600,
  },
  badge: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: 'var(--accent)',
    background: 'var(--accent-subtle)',
    padding: '3px 6px',
    borderRadius: 999,
  },
  bodyText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: 'var(--text-secondary)',
  },
  statRow: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  stat: {
    fontSize: 11,
    color: 'var(--text-muted)',
  },
  sourceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  sourceItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: '8px 10px',
    borderRadius: 8,
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
  },
  sourceLink: {
    fontSize: 12,
    color: 'var(--accent)',
    textDecoration: 'none',
  },
  sourceMeta: {
    fontSize: 11,
    color: 'var(--text-muted)',
    lineHeight: 1.4,
  },
  sourceNote: {
    fontSize: 12,
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  },
  evidenceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    margin: 0,
    paddingLeft: 18,
  },
  evidenceItem: {
    fontSize: 12,
    lineHeight: 1.5,
    color: 'var(--text-secondary)',
  },
  feedbackRow: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  feedbackButton: {
    padding: '5px 8px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--bg-secondary)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: 11,
  },
  feedbackButtonActive: {
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
    background: 'var(--accent-subtle)',
  },
  feedbackButtonDisabled: {
    cursor: 'default',
    opacity: 0.72,
  },
  feedbackError: {
    fontSize: 11,
    color: 'var(--status-error)',
    lineHeight: 1.4,
  },
}
