export const NORWEGIAN_CITY_NAMES = [
  'Oslo',
  'Bergen',
  'Trondheim',
  'Stavanger',
  'Tromsø',
  'Kristiansand',
  'Drammen',
  'Fredrikstad',
  'Sarpsborg',
  'Skien',
  'Ålesund',
  'Sandnes',
  'Tønsberg',
  'Moss',
  'Bodø',
  'Arendal',
  'Hamar',
  'Larvik',
  'Halden',
  'Molde',
  'Lillestrøm',
  'Hønefoss',
  'Kongsberg',
  'Gjøvik',
  'Harstad',
  'Narvik',
  'Alta',
  'Hammerfest',
  'Sortland',
  'Svolvær',
  'Fauske',
  'Levanger',
  'Namsos',
  'Steinkjer',
  'Florø',
  'Førde',
  'Kristiansund',
  'Voss',
  'Jessheim',
  'Elverum',
  'Porsgrunn',
  'Sandefjord',
  'Kongsvinger',
  'Notodden',
  'Lillehammer',
  'Egersund',
  'Farsund',
  'Mandal',
  'Mo i Rana',
  'Stjørdal',
] as const

export function pickRandomNorwegianCityName(random: () => number = Math.random): string {
  const index = Math.floor(random() * NORWEGIAN_CITY_NAMES.length)
  return NORWEGIAN_CITY_NAMES[index] ?? NORWEGIAN_CITY_NAMES[0]
}
