import type React from 'react'
import { createDialogStyles, dialogPrimitives } from '../workbench-style-primitives'

const base = createDialogStyles('480px')

export const modalStyles: Record<string, React.CSSProperties> = {
  ...base,
  input: {
    ...base.input,
    padding: '0 var(--space-md)',
    fontFamily: 'var(--font-mono)',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
  },
  subTabBar: {
    display: 'flex',
    gap: 'var(--space-xs)',
    marginBottom: 'var(--space-xs)',
  },
  subTab: {
    minHeight: 'calc(var(--control-height) - 4px)',
    padding: '0 var(--space-md)',
    fontSize: 'var(--type-ui-caption)',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    background: 'var(--control-bg)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
  },
  subTabActive: {
    color: 'var(--text-primary)',
    background: 'var(--bg-chrome-active)',
    borderColor: 'var(--accent)',
  },
  errorText: dialogPrimitives.errorText,
  infoText: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-muted)',
    margin: 0,
    fontStyle: 'italic',
  },
  advancedToggle: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 'var(--space-xs) var(--space-sm)',
    margin: '0 calc(-1 * var(--space-sm))',
  },
  infoCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
    padding: 'var(--space-md)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-md)',
    background: 'var(--bg-secondary)',
  },
  infoCardTitle: {
    fontSize: 'var(--type-ui-small)',
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  infoCardText: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  },
  infoCardList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  infoCardRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-md)',
    paddingTop: 'var(--space-sm)',
    borderTop: '1px solid var(--border-subtle, var(--border))',
  },
  infoCardPrimary: {
    fontSize: 'var(--type-ui-small)',
    fontWeight: 500,
    color: 'var(--text-primary)',
  },
  infoCardSecondary: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
  },
  infoCardContext: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-secondary)',
    lineHeight: 1.45,
  },
  infoCardMeta: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    opacity: 0.85,
    fontFamily: 'var(--font-mono)',
  },
  infoCardActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-xs)',
    flexShrink: 0,
  },
  inlineActionButton: {
    minHeight: '28px',
    padding: '0 var(--space-md)',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'var(--control-bg)',
    color: 'var(--text-primary)',
    fontSize: 'var(--type-ui-caption)',
    cursor: 'pointer',
  },
  inlineDangerButton: {
    minHeight: '28px',
    padding: '0 var(--space-md)',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid color-mix(in srgb, var(--error) 55%, var(--border))',
    background: 'color-mix(in srgb, var(--error) 12%, var(--bg-secondary))',
    color: 'var(--error)',
    fontSize: 'var(--type-ui-caption)',
    cursor: 'pointer',
  },
}
