import type React from 'react'
import { createDialogStyles } from '../workbench-style-primitives'

const base = createDialogStyles('720px')

export const modalStyles: Record<string, React.CSSProperties> = {
  ...base,
  panel: {
    ...base.panel,
    width: 'min(720px, calc(100vw - 32px))',
    maxWidth: 'calc(100vw - 32px)',
    maxHeight: 'calc(100vh - 32px)',
    display: 'flex',
    flexDirection: 'column',
  },
  body: {
    ...base.body,
    padding: 0,
    gap: 0,
    flex: 1,
    minHeight: 0,
  },
  settingsLayout: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
  },
  tabBar: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    padding: 'var(--space-md) var(--space-lg)',
    borderBottom: '1px solid var(--border)',
    background: 'linear-gradient(180deg, var(--bg-chrome), color-mix(in srgb, var(--bg-overlay) 96%, transparent))',
    flexShrink: 0,
  },
  tab: {
    flex: '1 1 220px',
    minHeight: '52px',
    padding: '10px 14px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: '4px',
    textAlign: 'left',
    color: 'var(--text-secondary)',
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
  },
  tabActive: {
    color: 'var(--text-primary)',
    background: 'color-mix(in srgb, var(--accent) 12%, var(--bg-elevated))',
    borderColor: 'color-mix(in srgb, var(--accent) 50%, var(--control-border))',
    boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--accent) 18%, transparent)',
  },
  tabTitle: {
    fontSize: 'var(--type-ui)',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  tabDescription: {
    fontSize: 'var(--type-ui-caption)',
    lineHeight: 1.4,
    color: 'var(--text-muted)',
  },
  tabPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-lg)',
    padding: 'var(--space-lg)',
    overflowY: 'auto',
    flex: 1,
    minHeight: 0,
  },
  sectionHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  sectionHeading: {
    color: 'var(--text-primary)',
    fontSize: 'calc(var(--type-ui) + 2px)',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  sectionDescription: {
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
    lineHeight: 1.5,
    maxWidth: '60ch',
  },
  cardGrid: {
    display: 'grid',
    gap: 'var(--space-lg)',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    alignItems: 'start',
  },
  sectionCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-md)',
    padding: 'var(--space-lg)',
    background: 'color-mix(in srgb, var(--bg-elevated) 90%, var(--bg-overlay))',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-md)',
  },
  cardHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  cardTitle: {
    color: 'var(--text-primary)',
    fontSize: 'var(--type-ui)',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  cardDescription: {
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-caption)',
    lineHeight: 1.5,
  },
  fieldGrid: {
    display: 'grid',
    gap: 'var(--space-md)',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    alignItems: 'start',
  },
  fieldSpanFull: {
    gridColumn: '1 / -1',
  },
  checkboxField: {
    ...base.label,
    flexDirection: 'row',
    alignItems: 'center',
    gap: '8px',
    color: 'var(--text-primary)',
  },
  checkboxInput: {
    width: 'auto',
    margin: 0,
    accentColor: 'var(--accent)',
  },
  themeButton: {
    width: '100%',
    minHeight: 'var(--control-height)',
    padding: '0 var(--space-sm)',
    fontSize: 'var(--type-ui)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    textAlign: 'left' as const,
    background: 'var(--control-bg)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
  },
  pickerContainer: {
    marginTop: 'var(--space-sm)',
    borderRadius: 'var(--radius-sm)',
    overflow: 'hidden',
    border: '1px solid var(--border)',
    background: 'var(--bg-primary)',
  },
  divider: {
    borderTop: '1px solid var(--border)',
    margin: '4px 0',
  },
  sectionTitle: {
    color: 'var(--text-primary)',
    fontSize: 'var(--type-ui-small)',
    fontWeight: 600,
  },
}
