export const THINKING_PHRASES = [
  'Bribing the brain cells',
  'Teaching the robots to dance',
  'Untangling the headphones',
  'Up, up and away',
  'Cha-chinging some ideas',
  'Warming up the hamsters',
  'Powering through it',
  'Beep-boop, computing',
  'Cha-ching and a prayer',
  'Easy come, easy go',
  'Cashing in some thoughts',
  'Feeding the idea goblins',
  'Cooking it like it’s hot',
  'Consulting the rubber duck',
  'Herding a few stray neurons',
  'Booting up the brain hamsters',
  'Doing a little think-dance',
  'Brb, thinking',
  'Polishing the punchline',
  'Greasing the thought gears',
  'Waking up the wise owls',
  'Hold the line, please',
  'Negotiating with my neurons',
  'Stretching before the heavy lifting',
  'Loading the good stuff',
  'Springing into action',
  'Convincing the gremlins to behave',
  'Shuffling the idea deck',
  'Tuning the thinking radio',
  'Almost got it',
  'Rounding up the loose thoughts',
  'Caffeinating the algorithms',
  'Doing the brainy hokey-pokey',
  'Pause and ponder',
  'Pestering the smart neurons',
  'Wrangling some wild ideas',
  'Defragging my brain',
  'Give me a sec',
  'Sharpening the mental pencils',
  'Asking the office plant',
  'Spinning up the idea blender',
  'Thinking cap on',
  'Nudging the lazy synapses',
  'Reading between the lines',
  'Polishing my crystal ball',
  'Computing the vibes',
  'Coaxing the answer out',
  'Doing some mental gymnastics',
  'Whispering to the algorithms',
  'Brain loading',
  'Stacking the building blocks',
  'Charging the idea batteries',
  'Consulting the wise toaster',
  'Sharpening the pixels',
  'Lassoing a clever thought',
  'Warming up the think muscles',
  'Knocking on wisdom’s door',
  'Plotting greatness',
  'Petting the algorithm cat',
  'Untangling a thought knot',
  'Brewing a fresh idea',
  'Cooking something up',
  'Dusting off the brain books',
  'Rallying the neuron troops',
  'Doing the thinky shuffle',
  'On the case',
  'Squeezing the idea sponge',
  'Flipping through the mind files',
  'Bargaining with the brain fog',
  'Gears turning',
  'Summoning a smart thought',
  'Polishing the lightbulb',
  'Feeding the curious cats',
  'Almost cooked',
  'Spinning the wisdom wheel',
  'Tickling the imagination',
  'Rebooting the daydream',
  'Nearly nailed it',
  'Chasing a runaway idea',
  'Loading wit, please hold',
  'Buttering up the brain',
  'Magic in progress',
  'Stirring the thought soup',
  'Recruiting some bright sparks',
  'Doing a quick brain stretch',
  'Weaving an answer',
  'Tapping the idea keg',
  'Counting clever sheep',
  'Polishing my act',
  'Big think happening',
  'Shaking out the cobwebs',
  'Befriending the brain bots',
  'Hatching a tiny plan',
  'Smart mode engaged',
  'Threading the thought needle',
  'Cranking the genius lever',
  'The wheels are turning',
  'Wrapping up a bright idea',
  'Doodling in the margins of my mind',
  'Polishing the final touch',
  'Tightening the loose bolts',
  'Inflating the idea balloon',
  'Buffering the brilliance',
  'Rinsing off a fresh thought',
  'Saddling up the synapses',
  'Knitting a neat answer',
  'Marinating the mind',
  'Filing down the rough edges',
  'Chasing the lightbulb moment',
  'Stoking the idea furnace',
  'Pinging the wisdom server',
  'Sweeping up stray sparks',
  'Whittling down the options',
  'Cuddling a complex thought',
  'Rebooting the genius engine',
  'Tipping over the idea jar',
  'Polishing a pearl of wisdom',
  'Spinning straw into thoughts',
  'Tuning the inner orchestra',
  'Counting on my fingers',
  'Wrestling a stubborn idea',
  'Pampering the brain cells',
  'Greasing the mental hinges',
  'Combing through the clues',
  'Decoding the doodles',
  'Stitching the story together',
  'Fueling up on think juice',
  'Rummaging the mind drawer',
  'Plucking a thought from the air',
  'Lighting the idea candle',
  'Massaging the metaphors',
  'Charging up the cleverness',
  'Sorting the mental laundry',
  'Polishing the brainware',
  'Negotiating with the deadline',
  'Topping up the wisdom tank',
  'Sketching a quick plan',
  'Wringing out the wet ideas',
  'Coaxing the gears to spin',
  'Sifting through the noise',
  'Hugging a hard problem',
  'Tickling the neurons awake',
  'Reeling in a big idea',
  'Polishing the rough draft',
  'Steeping the thoughts a bit',
  'Untwisting the logic',
  'Dialing in the focus',
  'Shaking the magic 8-ball',
  'Buttoning up the details',
  'Feeding quarters to the brain',
  'Lubing the thinking machine',
  'Rolling up my mental sleeves',
  'Pacing the imaginary hallway',
  'Doodling a master plan',
  'Catching the slippery thought',
  'Brushing off the brilliance',
  'Cranking up the curiosity',
  'Wading through the what-ifs',
  'Snacking on some data',
  'Polishing the cleverness',
  'Smoothing out the wrinkles',
  'Pep-talking the neurons',
  'Lining up the dominoes',
  'Wrenching loose a fresh idea',
  'Stretching the imagination',
  'Booting the brilliance.exe',
  'Mixing a clever cocktail',
  'Splashing cold water on the brain',
  'Patching the thought leaks',
  'Tuning into the right frequency',
  'Scooping up loose insights',
  'Untangling the spaghetti',
  'Recharging the wit reserves',
  'Folding the mental origami',
  'Convincing the muse to show up',
  'Polishing the plot twist',
  'Setting the idea oven to bake',
  'Knocking the dust off the gears',
  'Counting backwards from clever',
  'Buffing up the brainpower',
  'Reshelving the mind library',
  'Pinning down a wiggly idea',
  'Stretching out a long thought',
  'Tidying the thought closet',
  'Feeding the answer machine',
  'Whisking up some insight',
  'Cracking open the idea vault',
  'Massaging a knotty problem',
  'Spinning the mental rolodex',
  'Topping off the genius gauge',
  'Lassoing the loose ends',
  'Wiping the foggy windshield',
  'Pressing the big think button',
  'Stacking up the maybes',
  'Smoothing the mental gravel',
  'Petting the idea hedgehog',
  'Charging the imagination cells',
  'Plotting the next move',
  'Sweeping the brain floor',
  'Reeling the answer ashore',
  'Polishing a shiny conclusion',
  'Cranking the idea wheel',
  'Letting the gears warm up',
  'Hunting for the right word',
  'Stirring the imagination pot',
  'Defrosting a frozen idea',
  'Squinting at the fine print',
  'Tugging on a loose thread',
  'Feeding peanuts to the brain elephant',
  'Wrapping my head around it',
  'Inflating the brain balloon',
  'Tweaking the thought dials',
  'Climbing the idea ladder',
  'Sharpening the wit',
  'Brewing a strong conclusion',
  'Polishing the brass tacks',
  'Counting the moving parts',
  'Booting the daydream sequence',
  'Tinkering under the hood',
  'Flexing the gray matter',
  'Cueing up the eureka',
  'Steering toward the answer',
  'Mopping up the leftover doubts',
  'Whittling a sharper point',
  'Cradling a fragile idea',
  'Spinning up extra brain cores',
  'Reading the tea leaves',
  'Untying the mental shoelaces',
  'Hauling in the heavy thoughts',
  'Greasing the eureka slide',
  'Topping the sundae with insight',
  'Pressing play on the brain',
  'Rounding the last corner',
  'Stacking clever on top of clever',
  'Buffing the final answer',
  'Sweeping cobwebs off the plan',
  'Reheating yesterday’s genius',
  'Threading a tricky needle',
  'Polishing up the punch',
  'Catching the next brainwave',
  'Tidying the loose logic',
  'Charging into the deep end',
  'Knocking ideas into shape',
  'Smoothing the bumpy bits',
  'Feeding the thought furnace',
  'Pinning the tail on the answer',
  'Rallying the reluctant neurons',
  'Wringing wisdom from the rag',
  'Dusting the crystal ball',
  'Cranking out a clever bit',
  'Letting the idea simmer',
  'Pumping up the brain tires',
  'Sorting the keepers from the junk',
  'Snipping the red tape in my head',
  'Coaxing a shy idea forward',
  'Lining the ducks in a row',
  'Stoking the curiosity fire',
  'Polishing the gemstone thought',
  'Reorganizing the mind desk',
  'Spinning the answer roulette',
  'Tightening the mental screws',
  'Fishing in the idea pond',
  'Buttering up the muse',
  'Wheeling out the big brain',
  'Stretching the last neuron',
  'Tuning the genius guitar',
  'Patching together a plan',
  'Counting clever to ten',
  'Shaking the idea piggy bank',
  'Polishing the closing line',
  'Cooling the overheated thoughts',
  'Reeling back the wandering mind',
  'Stacking the puzzle pieces',
  'Warming the cold logic',
  'Pinching a thought from thin air',
  'Tidying up the thinking',
  'Charging the last idea cell',
  'Wrapping a bow on it',
  'Oiling the squeaky synapse',
  'Rallying the daydreamers',
  'Bouncing the idea ball',
  'Combing the thought beach',
  'Pressing the genius pedal',
  'Whisking away the confusion',
  'Stacking another smart brick',
  'Tugging the answer loose',
  'Polishing a quick comeback',
  'Hauling up the deep thoughts',
  'Tuning the mind dial',
  'Spinning a little harder',
  'Nudging the eureka along',
  'Sweeping in a fresh angle',
  'Letting the gears catch up',
  'Coaxing clarity to the surface',
  'Buffing out the confusion',
  'Reeling in the right words',
  'Plugging in the brain charger',
  'Smoothing the last rough edge',
  'Cresting the idea hill',
  'Sealing the clever deal',
]
