export const THINKING_PHRASES = [
  'Bribing the brain cells',
  'Teaching the robots to dance',
  'Untangling the headphones',
  'Up, up and away',
  'Cha-chinging some ideas',
  'Warming up the hamsters',
  'Powering through it',
  'Beep-boop, computing',
  'Cha-ching and a prayer',
  'Easy come, easy go',
  'Cashing in some thoughts',
  'Feeding the idea goblins',
  'Cooking it like it’s hot',
  'Consulting the rubber duck',
  'Herding a few stray neurons',
  'Booting up the brain hamsters',
  'Doing a little think-dance',
  'Brb, thinking',
  'Polishing the punchline',
  'Greasing the thought gears',
  'Waking up the wise owls',
  'Hold the line, please',
  'Negotiating with my neurons',
  'Stretching before the heavy lifting',
  'Loading the good stuff',
  'Springing into action',
  'Convincing the gremlins to behave',
  'Shuffling the idea deck',
  'Tuning the thinking radio',
  'Almost got it',
  'Rounding up the loose thoughts',
  'Caffeinating the algorithms',
  'Doing the brainy hokey-pokey',
  'Pause and ponder',
  'Pestering the smart neurons',
  'Wrangling some wild ideas',
  'Defragging my brain',
  'Give me a sec',
  'Sharpening the mental pencils',
  'Asking the office plant',
  'Spinning up the idea blender',
  'Thinking cap on',
  'Nudging the lazy synapses',
  'Reading between the lines',
  'Polishing my crystal ball',
  'Computing the vibes',
  'Coaxing the answer out',
  'Doing some mental gymnastics',
  'Whispering to the algorithms',
  'Brain loading',
  'Stacking the building blocks',
  'Charging the idea batteries',
  'Consulting the wise toaster',
  'Sharpening the pixels',
  'Lassoing a clever thought',
  'Warming up the think muscles',
  'Knocking on wisdom’s door',
  'Plotting greatness',
  'Petting the algorithm cat',
  'Untangling a thought knot',
  'Brewing a fresh idea',
  'Cooking something up',
  'Dusting off the brain books',
  'Rallying the neuron troops',
  'Doing the thinky shuffle',
  'On the case',
  'Squeezing the idea sponge',
  'Flipping through the mind files',
  'Bargaining with the brain fog',
  'Gears turning',
  'Summoning a smart thought',
  'Polishing the lightbulb',
  'Feeding the curious cats',
  'Almost cooked',
  'Spinning the wisdom wheel',
  'Tickling the imagination',
  'Rebooting the daydream',
  'Nearly nailed it',
  'Chasing a runaway idea',
  'Loading wit, please hold',
  'Buttering up the brain',
  'Magic in progress',
  'Stirring the thought soup',
  'Recruiting some bright sparks',
  'Doing a quick brain stretch',
  'Weaving an answer',
  'Tapping the idea keg',
  'Counting clever sheep',
  'Polishing my act',
  'Big think happening',
  'Shaking out the cobwebs',
  'Befriending the brain bots',
  'Hatching a tiny plan',
  'Smart mode engaged',
  'Threading the thought needle',
  'Cranking the genius lever',
  'The wheels are turning',
  'Wrapping up a bright idea',
  'Doodling in the margins of my mind',
  'Polishing the final touch',
  'Tightening the loose bolts',
  'Inflating the idea balloon',
  'Buffering the brilliance',
  'Rinsing off a fresh thought',
  'Saddling up the synapses',
  'Knitting a neat answer',
  'Marinating the mind',
  'Filing down the rough edges',
  'Chasing the lightbulb moment',
  'Stoking the idea furnace',
  'Pinging the wisdom server',
  'Sweeping up stray sparks',
  'Whittling down the options',
  'Cuddling a complex thought',
  'Rebooting the genius engine',
  'Tipping over the idea jar',
  'Polishing a pearl of wisdom',
  'Spinning straw into thoughts',
  'Tuning the inner orchestra',
  'Counting on my fingers',
  'Wrestling a stubborn idea',
  'Pampering the brain cells',
  'Greasing the mental hinges',
  'Combing through the clues',
  'Decoding the doodles',
  'Stitching the story together',
  'Fueling up on think juice',
  'Rummaging the mind drawer',
  'Plucking a thought from the air',
  'Lighting the idea candle',
  'Massaging the metaphors',
  'Charging up the cleverness',
  'Sorting the mental laundry',
  'Polishing the brainware',
  'Negotiating with the deadline',
  'Topping up the wisdom tank',
  'Sketching a quick plan',
  'Wringing out the wet ideas',
  'Coaxing the gears to spin',
  'Sifting through the noise',
  'Hugging a hard problem',
  'Tickling the neurons awake',
  'Reeling in a big idea',
  'Polishing the rough draft',
  'Steeping the thoughts a bit',
  'Untwisting the logic',
  'Dialing in the focus',
  'Shaking the magic 8-ball',
  'Buttoning up the details',
  'Feeding quarters to the brain',
  'Lubing the thinking machine',
  'Rolling up my mental sleeves',
  'Pacing the imaginary hallway',
  'Doodling a master plan',
  'Catching the slippery thought',
  'Brushing off the brilliance',
  'Cranking up the curiosity',
  'Wading through the what-ifs',
  'Snacking on some data',
  'Polishing the cleverness',
  'Smoothing out the wrinkles',
  'Pep-talking the neurons',
  'Lining up the dominoes',
  'Wrenching loose a fresh idea',
  'Stretching the imagination',
  'Booting the brilliance.exe',
  'Mixing a clever cocktail',
  'Splashing cold water on the brain',
  'Patching the thought leaks',
  'Tuning into the right frequency',
  'Scooping up loose insights',
  'Untangling the spaghetti',
  'Recharging the wit reserves',
  'Folding the mental origami',
  'Convincing the muse to show up',
  'Polishing the plot twist',
  'Setting the idea oven to bake',
  'Knocking the dust off the gears',
  'Counting backwards from clever',
  'Buffing up the brainpower',
  'Reshelving the mind library',
  'Pinning down a wiggly idea',
  'Stretching out a long thought',
  'Tidying the thought closet',
  'Feeding the answer machine',
  'Whisking up some insight',
  'Cracking open the idea vault',
  'Massaging a knotty problem',
  'Spinning the mental rolodex',
  'Topping off the genius gauge',
  'Lassoing the loose ends',
  'Wiping the foggy windshield',
  'Pressing the big think button',
  'Stacking up the maybes',
  'Smoothing the mental gravel',
  'Petting the idea hedgehog',
  'Charging the imagination cells',
  'Plotting the next move',
  'Sweeping the brain floor',
  'Reeling the answer ashore',
  'Polishing a shiny conclusion',
  'Cranking the idea wheel',
  'Letting the gears warm up',
  'Hunting for the right word',
  'Stirring the imagination pot',
  'Defrosting a frozen idea',
  'Squinting at the fine print',
  'Tugging on a loose thread',
  'Feeding peanuts to the brain elephant',
  'Wrapping my head around it',
  'Inflating the brain balloon',
  'Tweaking the thought dials',
  'Climbing the idea ladder',
  'Sharpening the wit',
  'Brewing a strong conclusion',
  'Polishing the brass tacks',
  'Counting the moving parts',
  'Booting the daydream sequence',
  'Tinkering under the hood',
  'Flexing the gray matter',
  'Cueing up the eureka',
  'Steering toward the answer',
  'Mopping up the leftover doubts',
  'Whittling a sharper point',
  'Cradling a fragile idea',
  'Spinning up extra brain cores',
  'Reading the tea leaves',
  'Untying the mental shoelaces',
  'Hauling in the heavy thoughts',
  'Greasing the eureka slide',
  'Topping the sundae with insight',
  'Pressing play on the brain',
  'Rounding the last corner',
  'Stacking clever on top of clever',
  'Buffing the final answer',
  'Sweeping cobwebs off the plan',
  'Reheating yesterday’s genius',
  'Threading a tricky needle',
  'Polishing up the punch',
  'Catching the next brainwave',
  'Tidying the loose logic',
  'Charging into the deep end',
  'Knocking ideas into shape',
  'Smoothing the bumpy bits',
  'Feeding the thought furnace',
  'Pinning the tail on the answer',
  'Rallying the reluctant neurons',
  'Wringing wisdom from the rag',
  'Dusting the crystal ball',
  'Cranking out a clever bit',
  'Letting the idea simmer',
  'Pumping up the brain tires',
  'Sorting the keepers from the junk',
  'Snipping the red tape in my head',
  'Coaxing a shy idea forward',
  'Lining the ducks in a row',
  'Stoking the curiosity fire',
  'Polishing the gemstone thought',
  'Reorganizing the mind desk',
  'Spinning the answer roulette',
  'Tightening the mental screws',
  'Fishing in the idea pond',
  'Buttering up the muse',
  'Wheeling out the big brain',
  'Stretching the last neuron',
  'Tuning the genius guitar',
  'Patching together a plan',
  'Counting clever to ten',
  'Shaking the idea piggy bank',
  'Polishing the closing line',
  'Cooling the overheated thoughts',
  'Reeling back the wandering mind',
  'Stacking the puzzle pieces',
  'Warming the cold logic',
  'Pinching a thought from thin air',
  'Tidying up the thinking',
  'Charging the last idea cell',
  'Wrapping a bow on it',
  'Oiling the squeaky synapse',
  'Rallying the daydreamers',
  'Bouncing the idea ball',
  'Combing the thought beach',
  'Pressing the genius pedal',
  'Whisking away the confusion',
  'Stacking another smart brick',
  'Tugging the answer loose',
  'Polishing a quick comeback',
  'Hauling up the deep thoughts',
  'Tuning the mind dial',
  'Spinning a little harder',
  'Nudging the eureka along',
  'Sweeping in a fresh angle',
  'Letting the gears catch up',
  'Coaxing clarity to the surface',
  'Buffing out the confusion',
  'Reeling in the right words',
  'Plugging in the brain charger',
  'Smoothing the last rough edge',
  'Cresting the idea hill',
  'Sealing the clever deal',
  'Reciting pneumonoultramicroscopicsilicovolcanoconiosis',
  'Recalling that honey never actually spoils',
  'Remembering octopuses have three hearts',
  'Noting a shrimp’s heart is in its head',
  'Pondering why wombat poop is cube-shaped',
  'Recalling bananas are berries but strawberries aren’t',
  'Remembering a group of flamingos is a flamboyance',
  'Noting that hot water can freeze faster than cold',
  'Recalling a bolt of lightning is hotter than the sun',
  'Remembering sea otters hold hands while sleeping',
  'Pondering that there are more stars than grains of sand',
  'Noting cows have best friends and get stressed apart',
  'Recalling the shortest war lasted just 38 minutes',
  'Remembering Venus has a day longer than its year',
  'Noting honeybees can recognize human faces',
  'Recalling the Eiffel Tower grows taller in summer',
  'Remembering sloths can hold their breath longer than dolphins',
  'Pondering that octopuses have blue blood',
  'Recalling a single cloud can weigh a million pounds',
  'Noting that Scotland’s national animal is the unicorn',
  'Remembering bubble wrap was first meant to be wallpaper',
  'Recalling humans share about 60% of their DNA with bananas',
  'Noting that a day on the Moon lasts about 29 Earth days',
  'Remembering the dot over a lowercase i is called a tittle',
  'Recalling that Oxford University is older than the Aztec Empire',
  'Pondering why the unicode for the longest word won’t fit',
  'Recalling that a group of crows is a murder',
  'Noting that bananas are mildly radioactive',
  'Remembering the inventor of the Frisbee was turned into one',
  'Pondering why “set” has more meanings than any other word',
  'Recalling that a jiffy is a real unit of time',
  'Noting the Great Wall isn’t actually visible from space',
  'Marveling that Cleopatra lived closer to the Moon landing than the pyramids',
  'Remembering that snails can sleep for three years',
  'Recalling an ostrich’s eye is bigger than its brain',
  'Pondering why “OK” is the world’s most spoken word',
  'Noting that hummingbirds can fly backwards',
  'Remembering that bananas float in water',
  'Recalling Nintendo was founded back in 1889',
  'Marveling that the Twitter bird was named Larry',
  'Noting that a group of pugs is called a grumble',
  'Recalling the smell of rain is called petrichor',
  'Remembering wombats can outsprint a human',
  'Pondering why pineapples take two years to grow',
  'Noting that apples, peaches, and pears are all roses',
  'Recalling that a shrimp can only swim backwards',
  'Remembering that butterflies taste with their feet',
  'Noting that a sneeze travels faster than a cheetah runs',
  'Recalling that humans glow faintly in the dark',
  'Pondering why a blue whale’s heart is the size of a car',
  'Marveling that a teaspoon of neutron star weighs a billion tons',
  'Remembering that Saturn would float in a big enough bathtub',
  'Noting that there’s enough gold in the Sun to coat the Earth',
  'Recalling that Pluto hasn’t made a full orbit since its discovery',
  'Remembering that one day on Venus spins backwards',
  'Pondering why Jupiter has at least 95 moons',
  'Noting that the Sun makes up 99.8% of the solar system’s mass',
  'Recalling that space smells faintly of seared steak',
  'Marveling that footprints on the Moon could last millions of years',
  'Remembering that a year on Mercury is just 88 days',
  'Noting that it rains diamonds on Neptune',
  'Recalling that the Milky Way smells of raspberries and rum',
  'Pondering why galaxies outnumber the stars in our own',
  'Remembering that sunlight takes 8 minutes to reach us',
  'Noting that a comet’s tail always points away from the Sun',
  'Recalling that astronauts grow taller in space',
  'Marveling that the universe is beige on average',
  'Remembering that days grow longer by milliseconds each century',
  'Noting that Earth bulges a bit at its middle',
  'Recalling that there are more trees on Earth than stars in the galaxy',
  'Pondering why the Atlantic gets wider every year',
  'Remembering that Mount Everest grows taller each year',
  'Noting that the Pacific is bigger than all the land combined',
  'Recalling that Antarctica is technically the largest desert',
  'Marveling that lightning strikes Earth 100 times a second',
  'Remembering that the deepest ocean trench is 7 miles down',
  'Noting that 90% of the ocean is still unexplored',
  'Recalling that a lightning bolt could toast a lot of bread',
  'Pondering why no two snowflakes are ever quite the same',
  'Remembering that some clouds drift faster than a highway car',
  'Noting that the Sahara was green just a few thousand years ago',
  'Recalling that rivers can flow uphill under the right conditions',
  'Marveling that the Amazon makes a fifth of the world’s oxygen',
  'Remembering that a single oak can drop 10,000 acorns a year',
  'Noting that bamboo can grow nearly a meter in a day',
  'Recalling that trees can warn each other through underground fungi',
  'Pondering why sunflowers turn to follow the sun',
  'Remembering that a strawberry wears its seeds on the outside',
  'Noting that carrots used to be purple',
  'Recalling that a tomato is botanically a fruit',
  'Marveling that peanuts aren’t actually nuts',
  'Remembering that cashews grow attached to a fruit',
  'Noting that chili heat is measured in Scoville units',
  'Recalling that vanilla is the second-most-expensive spice',
  'Pondering why wasabi is usually just dyed horseradish',
  'Remembering that honey from ancient tombs is still edible',
  'Noting that ketchup was once sold as medicine',
  'Recalling that carrots were bred orange to honor Dutch royalty',
  'Marveling that an avocado is a giant berry',
  'Remembering that watermelons are 92% water',
  'Noting that a fresh egg sinks and an old one floats',
  'Recalling that chocolate was once used as currency',
  'Pondering why almonds belong to the peach family',
  'Remembering that the fear of long words has a very long name',
  'Noting that “buffalo” can be a sentence eight times over',
  'Recalling that the shortest complete sentence is “Go.”',
  'Marveling that “bookkeeper” has three double letters in a row',
  'Remembering that “rhythms” is the longest word without a vowel',
  'Noting that “e” is the most common letter in English',
  'Recalling that “almost” has its letters in alphabetical order',
  'Pondering why the ampersand was once the 27th letter',
  'Remembering that the hashtag is properly an octothorpe',
  'Noting that “strengths” is the longest one-syllable word',
  'Recalling that “queue” is a Q with four silent letters',
  'Marveling that “dreamt” is the only word ending in “mt”',
  'Remembering that “uncopyrightable” repeats no letters',
  'Noting that emoji means “picture word” in Japanese',
  'Recalling that the exclamation mark is nicknamed a bang',
  'Pondering why a misheard lyric is called a mondegreen',
  'Remembering that the plural of octopus is octopuses',
  'Noting that a “quire” is 25 sheets of paper',
  'Recalling that a baby puffin is called a puffling',
  'Marveling that a group of owls is a parliament',
  'Remembering that a group of jellyfish is a smack',
  'Noting that a group of ferrets is a business',
  'Recalling that a group of rhinos is a crash',
  'Pondering why a group of porcupines is a prickle',
  'Remembering that a baby hedgehog is a hoglet',
  'Noting that a group of kittens is a kindle',
  'Recalling that a group of zebras is a dazzle',
  'Marveling that a baby kangaroo starts smaller than a jellybean',
  'Remembering that a giraffe’s tongue can be 20 inches long',
  'Noting that giraffes and humans share the same number of neck bones',
  'Recalling that elephants are the only animals that can’t jump',
  'Pondering why a tiger’s skin is striped, not just its fur',
  'Remembering that a polar bear’s skin is actually black',
  'Noting that a flamingo gets its pink from its food',
  'Recalling that penguins propose with a pebble',
  'Marveling that dolphins have names for each other',
  'Remembering that a crocodile can’t stick out its tongue',
  'Noting that a koala’s fingerprints look like a human’s',
  'Recalling that a sea cucumber can breathe through its bottom',
  'Pondering why a starfish has no brain at all',
  'Remembering that a jellyfish is 95% water',
  'Noting that some jellyfish may be effectively immortal',
  'Recalling that a snail can have thousands of tiny teeth',
  'Marveling that a slug has four noses',
  'Remembering that an earthworm has five hearts',
  'Noting that a leech has 32 brains',
  'Recalling that a cockroach can live a week without its head',
  'Pondering why a housefly hums in the key of F',
  'Remembering that a single ant can lift many times its weight',
  'Noting that ants don’t sleep the way we do',
  'Recalling that a bee visits two million flowers for one jar of honey',
  'Marveling that a bee’s buzz is its wings beating 200 times a second',
  'Remembering that mosquitoes are drawn to the color blue',
  'Noting that dragonflies are older than the dinosaurs',
  'Recalling that a butterfly was once called a flutterby',
  'Pondering why some moths have no mouth at all',
  'Remembering that spiders can balloon across the sky on silk',
  'Noting that spider silk is stronger than steel by weight',
  'Recalling that a frog can freeze solid and survive',
  'Marveling that a toad drinks water through its skin',
  'Remembering that a chameleon’s tongue is longer than its body',
  'Noting that a gecko can climb glass with tiny hairs',
  'Recalling that a turtle can breathe through its rear end',
  'Pondering why some turtles outlive a century',
  'Remembering that a snake smells with its tongue',
  'Noting that a snake’s heart can slide around its body',
  'Recalling that a Komodo dragon’s bite is mildly venomous',
  'Marveling that an axolotl can regrow almost anything',
  'Remembering that the seahorse dad is the one who gives birth',
  'Noting that a pufferfish is wildly poisonous',
  'Recalling that an electric eel can deliver 600 volts',
  'Pondering why a goldfish sees more colors than we do',
  'Remembering that sharks existed before trees did',
  'Noting that some sharks can live for 400 years',
  'Recalling that a whale’s song can travel for miles',
  'Marveling that a narwhal’s tusk is really a giant tooth',
  'Remembering that a blue whale’s tongue weighs as much as an elephant',
  'Noting that a dolphin sleeps with half its brain awake',
  'Recalling that an octopus can taste with its arms',
  'Pondering why an octopus can squeeze through a coin-sized gap',
  'Remembering that a squid can have eyes the size of dinner plates',
  'Noting that a cuttlefish can hypnotize prey with skin patterns',
  'Recalling that a lobster’s blood is blue',
  'Marveling that lobsters were once prison food',
  'Remembering that a crab walks sideways because of its joints',
  'Noting that a mantis shrimp can punch like a bullet',
  'Recalling that a mantis shrimp sees colors we can’t imagine',
  'Pondering why a starfish can regrow from a single arm',
  'Remembering that coral is an animal, not a plant',
  'Noting that a sponge has no organs at all',
  'Recalling that plankton make most of our planet’s oxygen',
  'Marveling that a single drop of seawater teems with life',
  'Remembering that the ocean holds millions of tons of gold',
  'Noting that waves can travel across an entire ocean',
  'Recalling that the loudest sound ever was a volcano erupting',
  'Pondering why a volcano can build brand-new islands',
  'Remembering that diamonds rain on Saturn too',
  'Noting that the body has enough carbon for 900 pencils',
  'Recalling that your stomach gets a new lining every few days',
  'Marveling that the human nose can detect a trillion scents',
  'Remembering that your body holds more bacteria than human cells',
  'Noting that bones are stronger than steel by weight',
  'Recalling that the smallest bone hides inside your ear',
  'Pondering why you’re a centimeter taller in the morning',
  'Remembering that your fingerprints are utterly unique',
  'Noting that your tongue print is unique too',
  'Recalling that babies are born with around 300 bones',
  'Marveling that adults have only 206 bones',
  'Remembering that your heart beats about 100,000 times a day',
  'Noting that your blood vessels could circle the Earth a few times',
  'Recalling that your brain uses about 20% of your energy',
  'Pondering why the brain has no pain receptors of its own',
  'Remembering that you can’t tickle yourself',
  'Noting that a yawn might be a way to cool the brain',
  'Recalling that goosebumps are a leftover from furrier ancestors',
  'Marveling that you blink around 20,000 times a day',
  'Remembering that the eye can tell apart millions of colors',
  'Noting that your ears never stop growing',
  'Recalling that taste is mostly powered by smell',
  'Pondering why the jaw is the strongest muscle for its size',
  'Remembering that the appendix may not be so useless after all',
  'Noting that humans are the only animals with chins',
  'Recalling that laughing is good for the heart',
  'Marveling that a single sneeze fires out 40,000 droplets',
  'Remembering that hair can reveal what you ate months ago',
  'Noting that nails grow faster on your dominant hand',
  'Recalling that you share much of your DNA with a fruit fly',
  'Pondering why DNA unwound would stretch to the Sun and back',
  'Remembering that identical twins don’t share fingerprints',
  'Noting that the first computer bug was a literal moth',
  'Recalling that the first webcam watched a coffee pot',
  'Marveling that the first website is still online today',
  'Remembering that more than half of internet traffic is bots',
  'Noting that QWERTY was designed to slow typists down',
  'Recalling that the first email was sent in 1971',
  'Pondering why a “byte” was almost called a “bite”',
  'Remembering that the save icon outlived the floppy disk',
  'Noting that the first computer mouse was made of wood',
  'Recalling that Wi-Fi doesn’t actually stand for anything',
  'Marveling that the first YouTube video was about a zoo',
  'Remembering that a programming language is named after a comedy troupe',
  'Noting that the term “bug” predates computers',
  'Recalling that the first hard drive could barely hold a song',
  'Pondering why a web search uses less energy than a sneeze',
  'Remembering that the “cloud” is really someone else’s computer',
  'Noting that the first tweet went out in 2006',
  'Recalling that the first photograph took eight hours to expose',
  'Marveling that the microwave was discovered by a melted candy bar',
  'Remembering that bubble gum is pink because that dye was left over',
  'Noting that the Eiffel Tower was meant to be temporary',
  'Recalling that the Statue of Liberty was once shiny copper',
  'Pondering why the Leaning Tower started leaning mid-build',
  'Remembering that the Mona Lisa has no eyebrows',
  'Noting that Big Ben is the bell, not the tower',
  'Recalling that the White House was painted to hide scorch marks',
  'Marveling that Venice rests on millions of wooden poles',
  'Remembering that the Great Pyramid was tallest for 3,800 years',
  'Noting that Stonehenge is older than the pyramids',
  'Recalling that Rome has a cat sanctuary in ancient ruins',
  'Pondering why the Colosseum could be flooded for mock sea battles',
  'Remembering that the Hawaiian alphabet has only 13 letters',
  'Noting that one Norwegian town goes months without a sunset',
  'Recalling that Russia spans eleven time zones',
  'Marveling that Canada has more lakes than the rest of the world combined',
  'Remembering that the Sahara can get snow on rare occasions',
  'Noting that the Dead Sea is so salty you simply float',
  'Recalling that Australia is wider than the Moon',
  'Pondering why Iceland grows bananas with geothermal heat',
  'Remembering that Japan has thousands of barely-visited islands',
  'Noting that the shortest place name is just one letter',
  'Recalling that the longest place name has 85 letters',
  'Marveling that Everest isn’t the closest point to space',
  'Remembering that the driest place has gone centuries without rain',
  'Noting that one lake can turn animals into stony statues',
  'Recalling that the world’s largest living thing is a giant fungus',
  'Pondering why a tardigrade can survive in outer space',
  'Remembering that a tardigrade shrugs off being frozen and boiled',
  'Noting that some bacteria thrive in near-boiling springs',
  'Recalling that the oldest living tree is over 4,800 years old',
  'Marveling that an aspen grove can be one giant organism',
  'Remembering that mushrooms are closer to animals than plants',
  'Noting that a slime mold can solve a maze without a brain',
  'Recalling that thunder is the sound of air exploding outward',
  'Pondering why no one knows exactly how many stars exist',
  'Remembering that a rainbow is actually a full circle',
  'Noting that a double rainbow has its colors reversed',
  'Recalling that the green flash at sunset is real, not a myth',
  'Marveling that auroras can hum and crackle faintly',
  'Remembering that fog is simply a cloud touching the ground',
  'Noting that a group of flamingos wading is a flamboyance on the move',
  'Recalling that a cat has 32 muscles in each ear',
  'Marveling that a snail can regrow its eyes',
  'Remembering that the unicorn outranks the lion on a royal crest',
  'Noting that a duck’s quack does echo, despite the myth',
  'Recalling that wombat poop is cube-shaped to stay put',
  'Pondering why penguins can’t taste sweet or savory flavors',
  'Remembering that a hippo’s sweat works as natural sunscreen',
]
