import type React from 'react'

export const viewerStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    padding: '4px 8px',
    borderBottom: '1px solid var(--border)',
    background: 'var(--bg-secondary)',
    flexShrink: 0,
  },
  headerText: {
    fontSize: 'inherit',
    fontWeight: 500,
    color: 'var(--text-secondary)',
  },
  tabBar: {
    display: 'flex',
    alignItems: 'center',
    borderBottom: '1px solid var(--border)',
    background: 'var(--bg-secondary)',
    flexShrink: 0,
    minWidth: 0,
  },
  tabStrip: {
    display: 'flex',
    alignItems: 'center',
    overflowX: 'auto' as const,
    overflowY: 'hidden' as const,
    minWidth: 0,
    flex: 1,
  },
  tabActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    paddingRight: '4px',
    flexShrink: 0,
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 8px',
    fontSize: 'inherit',
    color: 'var(--text-muted)',
    borderRight: '1px solid var(--border)',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    flexShrink: 0,
  },
  tabActive: {
    color: 'var(--text-primary)',
    background: 'var(--bg-primary)',
  },
  tabLabel: {
    padding: 0,
    fontSize: 'inherit',
    fontFamily: 'var(--font-mono)',
    color: 'inherit',
  },
  tabClose: {
    padding: '0 2px',
    fontSize: '14px',
    lineHeight: 1,
    color: 'var(--text-muted)',
    borderRadius: '3px',
  },
  previewToggle: {
    padding: '2px 8px',
    fontSize: '0.92em',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    background: 'var(--bg-input)',
    borderRadius: '3px',
    border: '1px solid var(--border)',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    flexShrink: 0,
  },
  actionButton: {
    padding: '2px 8px',
    fontSize: '0.92em',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    background: 'var(--bg-input)',
    borderRadius: '3px',
    border: '1px solid var(--border)',
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
    flexShrink: 0,
  },
  previewToggleActive: {
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
  },
  closeButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '18px',
    height: '18px',
    borderRadius: '3px',
    color: 'var(--text-muted)',
    fontSize: '14px',
    lineHeight: 1,
    cursor: 'pointer',
    flexShrink: 0,
    marginRight: '4px',
  },
  htmlPreview: {
    width: '100%',
    height: '100%',
    border: 'none',
    background: '#ffffff',
  },
  editorContainer: {
    flex: 1,
    overflow: 'hidden',
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: '13px',
  },
}
