import type React from 'react'
import type { FileChangeType } from '../../../shared/types'

export const CHANGE_INDICATORS: Record<FileChangeType, { color: string; label: string }> = {
  modified: { color: 'var(--warning)', label: 'M' },
  added: { color: 'var(--success)', label: 'A' },
  deleted: { color: 'var(--error)', label: 'D' },
}

export const treeStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
    position: 'relative' as const,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '4px 8px',
    borderBottom: '1px solid var(--border)',
    background: 'var(--bg-secondary)',
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: '11px',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  changesButton: {
    fontSize: '10px',
    color: 'var(--accent)',
    padding: '1px 6px',
    borderRadius: '8px',
    background: 'rgba(79, 195, 247, 0.12)',
  },
  closeButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '18px',
    height: '18px',
    borderRadius: '3px',
    color: 'var(--text-muted)',
    fontSize: '14px',
    lineHeight: 1,
    cursor: 'pointer',
  },
  treeContainer: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '2px 0',
    position: 'relative' as const,
  },
  treeContainerDragActive: {
    background: 'color-mix(in srgb, var(--accent) 8%, transparent)',
    boxShadow: 'inset 0 0 0 1px color-mix(in srgb, var(--accent) 45%, transparent)',
  },
  node: {
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    height: '22px',
    paddingRight: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: 'var(--font-sans)',
    lineHeight: '22px',
    color: 'var(--text-primary)',
  },
  chevron: {
    width: '16px',
    height: '16px',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'transform 0.1s ease',
    color: 'var(--text-secondary)',
  },
  chevronSpacer: {
    width: '16px',
    flexShrink: 0,
  },
  fileIcon: {
    width: '16px',
    fontSize: '14px',
    flexShrink: 0,
    textAlign: 'center' as const,
    lineHeight: '16px',
  },
  fileIconImg: {
    width: '16px',
    height: '16px',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nodeName: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-sans)',
    fontSize: '13px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  indicator: {
    flexShrink: 0,
    fontSize: '11px',
    fontWeight: 600,
    marginLeft: 'auto',
  },
  deleteButton: {
    flexShrink: 0,
    fontSize: '12px',
    marginLeft: '4px',
    cursor: 'pointer',
    padding: '0 2px',
    borderRadius: '3px',
  },
  renameInput: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-mono)',
    fontSize: '12px',
    padding: '0 4px',
    border: '1px solid var(--accent)',
    borderRadius: '3px',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
    outline: 'none',
    lineHeight: '18px',
  },
  dialogOverlay: {
    position: 'absolute' as const,
    inset: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  dialog: {
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
    borderRadius: '8px',
    padding: '16px',
    maxWidth: '300px',
    width: '90%',
  },
  dialogTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    marginBottom: '8px',
  },
  dialogMessage: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
    lineHeight: '1.4',
    marginBottom: '16px',
  },
  dialogActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
  },
  dialogCancel: {
    fontSize: '12px',
    padding: '4px 12px',
    borderRadius: '4px',
    border: '1px solid var(--border)',
    background: 'transparent',
    color: 'var(--text-primary)',
    cursor: 'pointer',
  },
  dialogConfirm: {
    fontSize: '12px',
    padding: '4px 12px',
    borderRadius: '4px',
    border: 'none',
    background: 'var(--error)',
    color: '#fff',
    cursor: 'pointer',
  },
  filterContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: '4px 8px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  filterInput: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-sans)',
    fontSize: '12px',
    padding: '3px 6px',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
    outline: 'none',
  },
  filterClear: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '18px',
    height: '18px',
    marginLeft: '4px',
    borderRadius: '3px',
    color: 'var(--text-muted)',
    fontSize: '14px',
    cursor: 'pointer',
    background: 'transparent',
    border: 'none',
    flexShrink: 0,
  },
  statusBanner: {
    padding: '6px 8px',
    fontSize: '11px',
    lineHeight: 1.4,
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  statusBannerInfo: {
    color: 'var(--text-secondary)',
    background: 'color-mix(in srgb, var(--accent) 8%, var(--bg-secondary))',
  },
  statusBannerError: {
    color: '#fff',
    background: 'color-mix(in srgb, var(--error) 88%, black 12%)',
  },
  dropOverlay: {
    position: 'absolute' as const,
    inset: '8px',
    border: '1px dashed color-mix(in srgb, var(--accent) 60%, transparent)',
    borderRadius: '8px',
    pointerEvents: 'none' as const,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    padding: '10px',
    background: 'linear-gradient(180deg, transparent, color-mix(in srgb, var(--accent) 6%, transparent))',
  },
  dropOverlayLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    background: 'color-mix(in srgb, var(--bg-primary) 82%, transparent)',
    border: '1px solid color-mix(in srgb, var(--accent) 35%, transparent)',
    borderRadius: '999px',
    padding: '4px 8px',
  },
  panelTabBar: {
    display: 'flex',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
    background: 'var(--bg-secondary)',
  },
  panelTab: {
    flex: 1,
    padding: '6px 12px',
    fontSize: '11px',
    fontWeight: 500,
    textAlign: 'center' as const,
    cursor: 'pointer',
    color: 'var(--text-muted)',
    background: 'transparent',
    border: 'none',
    borderBottom: '2px solid transparent',
    transition: 'color 0.15s, border-color 0.15s',
  },
  panelTabActive: {
    color: 'var(--text-primary)',
    borderBottomColor: 'var(--accent)',
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: '12px',
  },
}
