import type React from 'react'

export const searchStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  inputContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: '8px',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  input: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-sans)',
    fontSize: '12px',
    padding: '4px 8px',
    border: '1px solid var(--border)',
    borderRadius: '4px',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
    outline: 'none',
  },
  results: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '2px 0',
  },
  fileHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 8px',
    fontSize: '12px',
    fontWeight: 600,
    color: 'var(--text-primary)',
    cursor: 'pointer',
    background: 'var(--bg-secondary)',
    borderBottom: '1px solid var(--border)',
  },
  matchCount: {
    fontSize: '10px',
    fontWeight: 400,
    color: 'var(--text-muted)',
    marginLeft: 'auto',
  },
  matchLine: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    padding: '2px 8px 2px 24px',
    fontSize: '12px',
    fontFamily: 'var(--font-mono)',
    cursor: 'pointer',
    color: 'var(--text-secondary)',
    lineHeight: '20px',
  },
  lineNumber: {
    flexShrink: 0,
    color: 'var(--text-muted)',
    minWidth: '32px',
    textAlign: 'right' as const,
    fontSize: '11px',
  },
  lineText: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  highlight: {
    background: 'rgba(255, 213, 79, 0.3)',
    color: 'var(--text-primary)',
    borderRadius: '2px',
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: '12px',
    padding: '16px',
    textAlign: 'center' as const,
  },
  searching: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
    color: 'var(--text-muted)',
    fontSize: '12px',
  },
}
