import type React from 'react'

export const searchStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflow: 'hidden',
    background: 'var(--bg-primary)',
  },
  inputContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: 'var(--space-sm)',
    borderBottom: '1px solid var(--border)',
    flexShrink: 0,
  },
  input: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-sans)',
    fontSize: 'var(--type-ui-small)',
    minHeight: 'var(--control-height)',
    padding: '0 var(--space-sm)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    background: 'var(--control-bg)',
    color: 'var(--text-primary)',
  },
  results: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '2px 0',
  },
  fileHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-xs)',
    padding: '4px var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    fontWeight: 600,
    color: 'var(--text-primary)',
    cursor: 'pointer',
    background: 'var(--bg-chrome)',
    borderBottom: '1px solid var(--border)',
  },
  matchCount: {
    fontSize: 'var(--type-ui-micro)',
    fontWeight: 400,
    color: 'var(--text-muted)',
    marginLeft: 'auto',
  },
  matchLine: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 'var(--space-sm)',
    padding: '2px var(--space-sm) 2px 24px',
    fontSize: 'var(--type-ui-small)',
    fontFamily: 'var(--font-mono)',
    cursor: 'pointer',
    color: 'var(--text-secondary)',
    lineHeight: '18px',
  },
  lineNumber: {
    flexShrink: 0,
    color: 'var(--text-muted)',
    minWidth: '32px',
    textAlign: 'right' as const,
    fontSize: 'var(--type-ui-caption)',
  },
  lineText: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  highlight: {
    background: 'rgba(255, 213, 79, 0.3)',
    color: 'var(--text-primary)',
    borderRadius: 'var(--radius-xs)',
  },
  empty: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
    padding: '16px',
    textAlign: 'center' as const,
  },
  searching: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
  },
}
