import type React from 'react'

export const sidebarStyles: Record<string, React.CSSProperties> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  list: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '4px 0',
  },
  item: {
    cursor: 'pointer',
    fontSize: 'inherit',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    marginTop: 0,
  },
  itemActive: {
    color: 'var(--text-primary)',
  },
  itemName: {
    flex: 1,
    minWidth: 0,
  },
  itemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: '4px',
    flexShrink: 0,
  },
  removeButton: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-muted)',
    padding: 0,
    lineHeight: 1,
    background: 'transparent',
  },
  agentItem: {
    cursor: 'pointer',
    margin: '0',
    width: '100%',
    textAlign: 'left' as const,
    fontSize: 'inherit',
    color: 'var(--text-primary)',
    background: 'transparent',
  },
  agentBranch: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-mono)',
    fontSize: 'inherit',
  },
  agentRuntime: {
    fontSize: 'var(--type-ui-caption)',
    flexShrink: 0,
  },
  agentDeleteButton: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-muted)',
    padding: 0,
    lineHeight: 1,
    flexShrink: 0,
    cursor: 'pointer',
    background: 'transparent',
  },
  empty: {
    padding: '16px 12px',
    color: 'var(--text-muted)',
    fontSize: 'inherit',
    textAlign: 'center' as const,
  },
  actions: {
    display: 'flex',
    gap: 'var(--space-xs)',
    padding: '8px',
    borderTop: '1px solid var(--border)',
  },
  actionButtonPrimary: {
    flex: 1,
    padding: '0 var(--space-sm)',
    background: 'var(--accent-subtle)',
    border: '1px solid transparent',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'inherit',
    fontWeight: 600,
    color: 'var(--accent)',
    textAlign: 'center' as const,
  },
  actionButton: {
    flex: 1,
    padding: '0 var(--space-sm)',
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'inherit',
    color: 'var(--text-primary)',
    textAlign: 'center' as const,
  },
  cloneForm: {
    display: 'flex',
    padding: '0 8px 8px',
    gap: '4px',
  },
  cloneInput: {
    flex: 1,
    fontSize: 'inherit',
    padding: '4px 8px',
  },
  cloneSubmit: {
    padding: '0 10px',
    background: 'var(--btn-bg)',
    color: 'var(--btn-text)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'inherit',
  },
  fetchMessage: {
    padding: '2px 14px 4px 24px',
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
  },
}
