import type React from 'react'

export const sidebarStyles: Record<string, React.CSSProperties> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  list: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '4px 0',
  },
  item: {
    cursor: 'pointer',
    fontSize: 'inherit',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    marginTop: 0,
  },
  itemActive: {
    color: 'var(--text-primary)',
  },
  itemName: {
    flex: 1,
    minWidth: 0,
  },
  nameInput: {
    flex: 1,
    minWidth: 0,
    font: 'inherit',
    fontWeight: 600,
    color: 'var(--text-primary)',
    background: 'var(--bg-input)',
    border: '1px solid var(--accent)',
    borderRadius: 'var(--radius-xs)',
    padding: '0 4px',
    outline: 'none',
  },
  itemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginLeft: '4px',
    flexShrink: 0,
  },
  removeButton: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-muted)',
    padding: 0,
    lineHeight: 1,
    background: 'transparent',
  },
  // When the base branch is behind origin, the fetch button becomes an accent
  // pill so the ↻ glyph stays visible next to the count, instead of a badge
  // overlapping (and hiding) the icon. Overrides the fixed 16px width/height
  // and muted color of .sidebar-icon-button.
  fetchPill: {
    width: 'auto',
    height: 'auto',
    gap: '3px',
    padding: '1px 6px',
    borderRadius: 'var(--radius-pill)',
    background: 'var(--accent)',
    color: 'var(--accent-text)',
    fontSize: 'var(--type-ui-small)',
    fontWeight: 700,
    lineHeight: 1,
    opacity: 1,
    boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.06)',
  },
  addButton: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--accent)',
    padding: 0,
    lineHeight: 1,
    background: 'transparent',
  },
  agentItem: {
    cursor: 'pointer',
    margin: '0',
    width: '100%',
    textAlign: 'left' as const,
    fontSize: 'inherit',
    color: 'var(--text-primary)',
    background: 'transparent',
  },
  agentBranch: {
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--font-mono)',
    fontSize: 'inherit',
  },
  agentRuntime: {
    fontSize: 'var(--type-ui-caption)',
    flexShrink: 0,
  },
  agentDeleteButton: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-muted)',
    padding: 0,
    lineHeight: 1,
    flexShrink: 0,
    cursor: 'pointer',
    background: 'transparent',
  },
  agentRenameButton: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    padding: 0,
    lineHeight: 1,
    flexShrink: 0,
    cursor: 'pointer',
    background: 'transparent',
  },
  agentNameInput: {
    fontFamily: 'var(--font-mono)',
    fontSize: 'inherit',
    fontWeight: 600,
  },
  empty: {
    padding: '16px 12px',
    color: 'var(--text-muted)',
    fontSize: 'inherit',
    textAlign: 'center' as const,
  },
  actions: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-xs)',
    padding: '8px',
    borderTop: '1px solid var(--border)',
  },
  actionsRow: {
    display: 'flex',
    gap: 'var(--space-xs)',
  },
  // Layout only — the metallic surface comes from .sidebar-action-button--primary,
  // which an inline background/color here would silently override.
  actionButtonPrimary: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: 'var(--control-height)',
    overflow: 'hidden',
    padding: '0 var(--space-sm)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'inherit',
    cursor: 'pointer',
    textAlign: 'center' as const,
  } as React.CSSProperties,
  actionButton: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: 'var(--control-height)',
    padding: '0 var(--space-sm)',
    background: 'transparent',
    border: '1px solid color-mix(in srgb, var(--accent), transparent 70%)',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--accent)',
    fontSize: 'var(--type-ui-small)',
    cursor: 'pointer',
    transition: 'border-color var(--duration-normal) var(--ease-premium), background var(--duration-normal) var(--ease-premium)',
  } as React.CSSProperties,
  cloneForm: {
    display: 'flex',
    padding: '0 8px 8px',
    gap: '4px',
  },
  cloneInput: {
    flex: 1,
    fontSize: 'inherit',
    padding: '4px 8px',
  },
  cloneSubmit: {
    padding: '0 10px',
    background: 'var(--btn-bg)',
    color: 'var(--btn-text)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'inherit',
  },
  fetchMessage: {
    padding: '2px 14px 4px 24px',
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 'var(--space-xs)',
    padding: '0 var(--space-sm)',
    marginBottom: 'var(--space-xs)',
  } as React.CSSProperties,
  sectionAddButton: {
    width: 22,
    height: 22,
    fontSize: '16px',
    fontWeight: 600,
    lineHeight: 1,
    color: 'var(--accent)',
    flexShrink: 0,
  } as React.CSSProperties,
  sectionDivider: {
    height: 1,
    background: 'color-mix(in srgb, var(--accent), transparent 94%)',
    margin: 'var(--space-sm) var(--space-xs)',
  } as React.CSSProperties,
  sectionLabelToggle: {
    fontSize: 'var(--type-label)',
    fontWeight: 500,
    letterSpacing: 'var(--tracking-wide)',
    textTransform: 'uppercase' as const,
    color: 'color-mix(in srgb, var(--accent), transparent 60%)',
    padding: '0 var(--space-sm)',
    marginBottom: 'var(--space-xs)',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    cursor: 'pointer',
    userSelect: 'none' as const,
    border: 0,
    background: 'transparent',
    fontFamily: 'inherit',
    textAlign: 'left' as const,
  } as React.CSSProperties,
  sectionHeaderToggle: {
    flex: 1,
    minWidth: 0,
    padding: 0,
    marginBottom: 0,
  } as React.CSSProperties,
  sectionCount: {
    fontSize: 'var(--type-label)',
    color: 'var(--text-muted)',
    marginLeft: '2px',
  } as React.CSSProperties,
  inactiveList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 0,
  } as React.CSSProperties,
  collapsedProject: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '6px var(--space-sm)',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
    transition: 'background var(--duration-normal) var(--ease-premium)',
  } as React.CSSProperties,
  miniStatusDots: {
    display: 'flex',
    gap: 3,
    alignItems: 'center',
  } as React.CSSProperties,
  miniDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    flexShrink: 0,
  } as React.CSSProperties,
}
