import type React from 'react'

export const loopPanelStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-sans)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 'var(--space-xs) var(--space-sm)',
    background: 'var(--bg-chrome)',
    borderBottom: '1px solid var(--border)',
    minHeight: 32,
  },
  title: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerActions: {
    display: 'flex',
    gap: 'var(--space-xs)',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: 'var(--space-sm)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
    gap: 'var(--space-sm)',
    padding: 'var(--space-lg)',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-xs)',
  },
  label: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  input: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    padding: '6px 8px',
    fontSize: 'var(--type-ui-small)',
    fontFamily: 'var(--font-mono)',
  },
  textarea: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    padding: '8px 10px',
    fontSize: 'var(--type-ui-small)',
    fontFamily: 'var(--font-mono)',
    minHeight: 140,
    resize: 'vertical',
    lineHeight: 1.5,
  },
  labelRow: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 'var(--space-sm)',
  },
  labelHint: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'none',
    letterSpacing: 0,
  },
  labelActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
  },
  aiButton: {
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    color: 'var(--accent)',
    borderRadius: 'var(--radius-sm)',
    padding: '2px 8px',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-sans)',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    transition: 'background 150ms ease, color 150ms ease',
  },
  aiButtonDisabled: {
    cursor: 'default',
    opacity: 0.6,
  },
  aiButtonBusy: {
    cursor: 'progress',
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
    animation: 'ai-pulse 1.4s ease-in-out infinite',
  },
  aiSparkle: {
    display: 'inline-block',
    transformOrigin: 'center',
  },
  aiSparkleBusy: {
    animation: 'spin 1.6s linear infinite',
  },
  pendingCard: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    padding: 'var(--space-md)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  pendingHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-primary)',
  },
  pendingPulse: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: 'var(--status-running)',
    animation: 'dot-blink 1.4s ease-in-out infinite',
    flexShrink: 0,
  },
  pendingMeta: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    gap: '4px var(--space-md)',
    fontSize: 'var(--type-ui-small)',
    alignItems: 'baseline',
  },
  pendingMetaLabel: {
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    fontSize: 'var(--type-ui-caption)',
    letterSpacing: 0.4,
  },
  pendingMetaValue: {
    color: 'var(--text-secondary)',
    fontFamily: 'var(--font-mono)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  pendingHint: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-muted)',
    lineHeight: 1.5,
  },
  pendingProgressTrack: {
    position: 'relative',
    height: 3,
    background: 'var(--bg-secondary)',
    borderRadius: 'var(--radius-xs)',
    overflow: 'hidden',
  },
  pendingProgressBar: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '25%',
    background: 'linear-gradient(90deg, transparent, var(--accent), transparent)',
    animation: 'loop-progress-sweep 1.8s ease-in-out infinite',
  },
  statusBarRunning: {
    position: 'relative',
    overflow: 'hidden',
  },
  statusBarShimmer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    overflow: 'hidden',
  },
  statusBarShimmerFill: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '25%',
    background: 'linear-gradient(90deg, transparent, var(--status-running), transparent)',
    animation: 'loop-progress-sweep 1.8s ease-in-out infinite',
  },
  intro: {
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    padding: 'var(--space-sm) var(--space-md)',
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  introTitle: {
    color: 'var(--text-primary)',
    fontSize: 'var(--type-ui-small)',
    fontWeight: 500,
  },
  introSection: {
    display: 'flex',
    gap: 'var(--space-sm)',
    alignItems: 'flex-start',
  },
  introTag: {
    color: 'var(--accent)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    minWidth: 48,
    paddingTop: 2,
  },
  introTagMuted: {
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    minWidth: 48,
    paddingTop: 2,
  },
  inputRow: {
    display: 'flex',
    gap: 'var(--space-sm)',
  },
  select: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    padding: '6px 8px',
    fontSize: 'var(--type-ui-small)',
  },
  primaryButton: {
    background: 'linear-gradient(135deg, var(--btn-bg), var(--btn-hover))',
    color: 'var(--btn-text)',
    border: 'none',
    height: 'var(--control-height)',
    borderRadius: 'var(--radius-sm)',
    padding: '0 var(--space-md)',
    fontSize: 'var(--type-ui-small)',
    cursor: 'pointer',
    transition: 'filter 200ms ease',
  },
  secondaryButton: {
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    color: 'var(--text-secondary)',
    height: 'var(--control-height)',
    borderRadius: 'var(--radius-sm)',
    padding: '0 var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    cursor: 'pointer',
    transition: 'background 200ms ease, color 200ms ease',
  },
  statusBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    padding: 'var(--space-xs) var(--space-sm)',
    background: 'var(--bg-secondary)',
    borderBottom: '1px solid var(--divider)',
    fontSize: 'var(--type-ui-small)',
  },
  stateDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    flexShrink: 0,
  },
  bestBadge: {
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
  },
  iterList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  iterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    padding: '6px 8px',
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'var(--type-ui-small)',
  },
  iterIndex: {
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
    minWidth: 32,
  },
  iterOutcome: {
    fontSize: 'var(--type-ui-caption)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
  },
  iterScore: {
    display: 'inline-flex',
    alignItems: 'baseline',
    gap: 4,
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--type-ui-caption)',
  },
  iterScoreLabel: {
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    opacity: 0.75,
  },
  iterScoreValue: {
    color: 'var(--accent-text)',
    fontWeight: 600,
    fontSize: 'var(--type-ui-small)',
  },
  iterReason: {
    color: 'var(--text-muted)',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  iterGroup: {
    display: 'flex',
    flexDirection: 'column',
  },
  iterRowClickable: {
    cursor: 'pointer',
  },
  iterToggle: {
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    flexShrink: 0,
  },
  iterJudgeOutput: {
    margin: '4px 0 0 0',
    padding: 'var(--space-sm)',
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    color: 'var(--text-secondary)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--type-ui-caption)',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    maxHeight: 320,
    overflow: 'auto',
  },
}

export const outcomeColors: Record<string, { bg: string; fg: string }> = {
  improved: { bg: 'color-mix(in srgb, var(--status-done) 18%, transparent)', fg: 'var(--status-done)' },
  regressed: { bg: 'color-mix(in srgb, var(--status-waiting) 18%, transparent)', fg: 'var(--status-waiting)' },
  failed: { bg: 'color-mix(in srgb, var(--status-error) 18%, transparent)', fg: 'var(--status-error)' },
  aborted: { bg: 'color-mix(in srgb, var(--text-muted) 18%, transparent)', fg: 'var(--text-muted)' },
}

export const stateColors: Record<string, string> = {
  idle: 'var(--text-muted)',
  running: 'var(--status-running)',
  paused: 'var(--status-waiting)',
  finished: 'var(--status-done)',
  error: 'var(--status-error)',
}
