import type React from 'react'

export const loopPanelStyles: Record<string, React.CSSProperties> = {
  wrapper: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: 'var(--bg-primary)',
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-sans)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 'var(--space-xs) var(--space-sm)',
    background: 'var(--bg-chrome)',
    borderBottom: '1px solid var(--border)',
    minHeight: 32,
  },
  title: {
    fontSize: 'var(--type-ui-small)',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerActions: {
    display: 'flex',
    gap: 'var(--space-xs)',
  },
  content: {
    flex: 1,
    overflow: 'auto',
    padding: 'var(--space-sm)',
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    color: 'var(--text-muted)',
    fontSize: 'var(--type-ui-small)',
    gap: 'var(--space-sm)',
    padding: 'var(--space-lg)',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-sm)',
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 'var(--space-xs)',
  },
  label: {
    fontSize: 'var(--type-ui-caption)',
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  input: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    padding: '6px 8px',
    fontSize: 'var(--type-ui-small)',
    fontFamily: 'var(--font-mono)',
  },
  inputRow: {
    display: 'flex',
    gap: 'var(--space-sm)',
  },
  select: {
    background: 'var(--bg-input)',
    color: 'var(--text-primary)',
    border: '1px solid var(--control-border)',
    borderRadius: 'var(--radius-sm)',
    padding: '6px 8px',
    fontSize: 'var(--type-ui-small)',
  },
  primaryButton: {
    background: 'linear-gradient(135deg, var(--btn-bg), var(--btn-hover))',
    color: 'var(--btn-text)',
    border: 'none',
    height: 'var(--control-height)',
    borderRadius: 'var(--radius-sm)',
    padding: '0 var(--space-md)',
    fontSize: 'var(--type-ui-small)',
    cursor: 'pointer',
    transition: 'filter 200ms ease',
  },
  secondaryButton: {
    background: 'var(--control-bg)',
    border: '1px solid var(--control-border)',
    color: 'var(--text-secondary)',
    height: 'var(--control-height)',
    borderRadius: 'var(--radius-sm)',
    padding: '0 var(--space-sm)',
    fontSize: 'var(--type-ui-small)',
    cursor: 'pointer',
    transition: 'background 200ms ease, color 200ms ease',
  },
  statusBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    padding: 'var(--space-xs) var(--space-sm)',
    background: 'var(--bg-secondary)',
    borderBottom: '1px solid var(--divider)',
    fontSize: 'var(--type-ui-small)',
  },
  stateDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    flexShrink: 0,
  },
  bestBadge: {
    background: 'var(--accent-subtle)',
    color: 'var(--accent)',
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
    fontSize: 'var(--type-ui-caption)',
    fontFamily: 'var(--font-mono)',
  },
  iterList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  iterRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-sm)',
    padding: '6px 8px',
    background: 'var(--bg-elevated)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    fontSize: 'var(--type-ui-small)',
  },
  iterIndex: {
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
    minWidth: 32,
  },
  iterOutcome: {
    fontSize: 'var(--type-ui-caption)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    padding: '1px 6px',
    borderRadius: 'var(--radius-xs)',
  },
  iterScore: {
    fontFamily: 'var(--font-mono)',
    color: 'var(--text-primary)',
  },
  iterReason: {
    color: 'var(--text-muted)',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
}

export const outcomeColors: Record<string, { bg: string; fg: string }> = {
  improved: { bg: 'color-mix(in srgb, var(--status-done) 18%, transparent)', fg: 'var(--status-done)' },
  regressed: { bg: 'color-mix(in srgb, var(--status-waiting) 18%, transparent)', fg: 'var(--status-waiting)' },
  failed: { bg: 'color-mix(in srgb, var(--status-error) 18%, transparent)', fg: 'var(--status-error)' },
  aborted: { bg: 'color-mix(in srgb, var(--text-muted) 18%, transparent)', fg: 'var(--text-muted)' },
}

export const stateColors: Record<string, string> = {
  idle: 'var(--text-muted)',
  running: 'var(--status-running)',
  paused: 'var(--status-waiting)',
  finished: 'var(--status-done)',
  error: 'var(--status-error)',
}
